// Copyright TagMan Ltd 2014: T 3.50 V tags/tm-3.5.6 C Wed Dec 17 14:17:32 2014
//
// Copyright © 2012 TagMan. All rights reserved. V tags/tm-3.5.6 R 12294 C 2012-12-12 10:33:25
(function(g,h){function l(a,e,d){if(2>arguments.length){b.util.log("`account` and `id` arguments are required","error");for(var f in this)delete this[f]}else{for(var i in d)"undefined"==typeof b.conf[i]&&b.util.log("Invalid property passed to Container constructor: "+i,"warning");d=d||{};this.param=d.param||{};this.account=a;this.id=this.baseId=e;this.tags=[];this._setOptions(d);this.host=this.host.replace(/^(?:https?:)?\/\//i,"");this.log=new b.Log(b.logOptions||d.log);this.log.container=this;d.tags&&
(d.tags instanceof b.Tag&&(d.tags=[d.tags]),this.addTags.apply(this,d.tags));(this.debugMode=d.debugMode||!1)&&this.log.setDebugMode();d.statRate&&this.log.setStatTypeRate("container",d.statRate);d.waitTest||(b.waitLatency=b.POLL_INTERVAL);this.blockCalls=0}}function k(){b.doTags(b.position.WINDOW_LOADED);var a=(new Date).getTime(),e=function(){for(var a=b._containers,e=0,d=a.length;e<d;e++){var g=a[e];if(!g.isLandingPageDisabled()&&!g.isTimedOut())for(var g=g.tags,h=0,l=g.length;h<l;h++){var j=g[h];
if(!j.hasExecuted()&&j.position<=b.position.WINDOW_LOADED)return!0}}return!1};if(e())var d=g.setInterval(function(){b.util.log("Timer calling doTags(DOTAGS_TIMER)...","debug");b.doTags(b.position.DOTAGS_TIMER);var f=3E4<(new Date).getTime()-a,i=e();if(f||!i)b.util.log("No more tags need servicing ("+!i+") or timed out ("+f+"), cancelling dotags timer","debug"),g.clearInterval(d)},1E4)}var r=function(){return!0},j=g.document;j.head||j.getElementsByTagName("head");var B,b=g.TMAN||(g.TMAN={});b.startTime||
(b.startTime=new Date);b.blockingTime=0;b.currentPosition=0;b.syncSafe=!1;b._secure="https:"==location.protocol;b.MAX_BLOCK_CALLS=400;b.getPageLoadTime=function(){return new Date-b.startTime};b.waitTest||(b.waitTest=!1);b.account={};b.POLL_INTERVAL=b.POLL_INTERVAL||100;b.MAX_COOKIE_LENGTH=4E3;b._doTagsCallback=!1;if(!b.util){var t;t="undefined"===typeof Array.isArray?function(a){return"[object Array]"===Object.prototype.toString.call(a)}:Array.isArray;var u;a:{var o=function(a,e){for(var b in this)w.call(this,
b)&&a.call(e,this[b],b,this)},w={}.hasOwnProperty,x="hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),F=x.length;for(u in{toString:!0})if("toString"===u){u=o;break a}u=function(a,e){o.call(this,a,e);for(var b=0,f;b<F;++b)w.call(this,f=x[b])&&a.call(e,this[f],f,this)}}b.util={elements:0,K:function(a){return a},extend:function(a,e){for(var b in e)a[b]=e[b];return a},isInIframe:function(){return g.top!=g?1:0},isArray:t,findById:function(a){if(!a)return null;
b.util.isArray(a)||(a=[a]);for(var e=0,d=a.length;e<d;e++)if(a[e]){var f=j.getElementById(a[e]);if(f)return f}return null},createImage:function(a){return(new Image).src=a},append:function(a,e){a.id||(a.id="tmap_"+b.util.elements++);if(e){if(!e.noOnload){var d=b.load.onLoad;"onreadystatechange"in a&&(a.onreadystatechange=function(){if(a.readyState==="complete"||a.readyState==="loaded"){a.onload=a.onerror=a.onreadystatechange=null;d.call(a,true)}});a.onload=function(){d.call(a,true)};a.onerror=function(){d.call(a,
false)};e.url||(e.url=a.src||a.data);e.id||(e.id=a.id);a.tagman={};a.tagman.handle=b.load.start(e);a.tagman.errorOK=e.errorOK?!0:!1;e.tag&&e.tag instanceof b.Tag&&(a.tagman.tag=e.handle);e.element=a}}else e={};if(j.body){var f;if(e.target)f=e.target;else if(e.tag)f=b.util.findById([b.position.makeName(e.tag.position),b.position.makeName(b.position.BOTTOM_BODY)]);else{if(b.client.isBodyAppendSafe())return j.body.appendChild(a),a.id;f=b.util.findById([b.position.makeName(b.currentPosition),b.position.makeName(b.position.BOTTOM_BODY)])}if(!f)if(f=
j.getElementsByTagName("div"),0<f.length)f=f[f.length-1];else if("SCRIPT"==a.nodeName)f=j.getElementsByTagName("script")[0].parentNode;else return!1;try{f.insertBefore(a,null)}catch(i){if("Unexpected call to method or property access."==(i.message||i)){b.util.log("WARNING!! failed to append to "+f.tagName+"."+f.id+", replacing element with a DIV","warning");var p=j.createElement("DIV");f.id&&(p.id=f.id);f.parentNode.replaceChild(p,f);p.insertBefore(a,null)}}}else f=j.getElementsByTagName("script")[0],
f.parentNode.insertBefore(a,f);return a.id},appendIframe:function(a,e,d){var f=j.createElement("iframe");e?(f.width="18px",f.height="18px"):(f.width="0",f.height="0");f.style.cssText="position:absolute;left:-999em;top:0";f.src=a;return b.util.append(f,d)},appendObject:function(a,e){var d=j.createElement("object");d.width=d.height=1;d.style.display="none";d.data=a;return b.util.append(d,e)},appendDiv:function(a,e){if(!a)return b.util.log("id compulsary for call to appendDiv, request ignored","error"),
!1;var d=j.createElement("div");d.id=a;e?d.innerHTML=e:d.style.display="none";return b.util.append(d)},appendCSS:function(a){var e=j.getElementsByTagName("head")[0];if(!a||!e)return!1;var d=j.createElement("link");d.id="tmcss_"+b.util.elements++;d.rel="stylesheet";d.type="text/css";d.href=a;d.media="screen";e.appendChild(d);return d.id},appendScript:function(a,e,d){if(!e&&b.syncSafe&&!b.client.canAsyncJS()&&(!d||!1!==d.defer)&&b.client.canDeferJS()&&b.client.canAccelerate(b._containers?b._containers[0]:
h))return d=d||{},d.defer=!0,b.util.writeScript(a,!1,d);var f=j.createElement("script");f.async=d&&!1===d.async?!1:!0;e?f.text=a:f.src=a;return b.util.append(f,d)},log:function(a,e){"undefined"!=typeof b._containers&&b._containers[0]&&b.Log&&b._containers[0].log instanceof b.Log?b._containers[0].log.error(a,e||"warning"):(null!==b.util.cookie("tmDebug")||"127.0.0.1"===location.host||"file:"===location.protocol)&&("object"===typeof console&&console.log)&&console.log("TagMan Init ["+e+"]:"+a)},getUID:function(){var a=
b.num.base92encode(+new Date,7),a=a+b.num.base92encode(Math.floor(1E4*Math.random()),2);return a+=b.num.base92encode(b.String.checksum(navigator.userAgent),5)},getProtocol:function(){return"https:"===location.protocol?"https://":"http://"},appendImage:function(a,e){var d=j.createElement("img");d.src=a;d.style.width=d.style.height=1;d.style.cssText="position:absolute;left:-999em;top:0;border:0;";return b.util.append(d,e)},killById:function(a){b.util.log("attempting to kill id "+a,"debug");if(!b.client.canKill())return!1;
try{var e=j.getElementById(a),d=["src","data","text"],f=0,i,p;if(!e)return b.util.log("element "+a+" not found, unable to kill","error"),!1;for(;i=d[f++];)if(i in e||f==d.length){if(!1!==(p=b.client[i+"Replacement"](e)))b.util.log("****** killById("+a+") - setting "+i+" of "+e.nodeName+" to "+p,"debug"),e[i]=p;return!0}}catch(g){b.util.log("error attempting to kill id "+a+":"+g.message,"debug")}b.util.log("***** removing node from dom: "+a+" / "+e.nodeNamei,"debug");e.parentNode&&e.parentNode.removeChild(e);
return!0},decode:function(a){return decodeURIComponent(a)},encode:function(a){return encodeURIComponent(a)},writeImage:function(a,e,d,f){if(!b.syncSafe)return b.util.log("ignoring unsafe attempt to document.write image ["+a+"]","error"),!1;var i="tmim_"+b.util.elements++,e='<img id="'+i+'" src="'+a+'" width="'+(e||1)+'" height="'+(d||1)+'" border="0"'+(e?"":' style="position:absolute;top:0;left:-999em"');f?(e+=" onload=\"TMAN.load.onLoadById('"+i+"', true);\" onerror=\"TMAN.load.onLoadById('"+i+"', false);\" />",
f.url=a,f.id=i,b.load.start(f)):e+=" />";b.util.log("writing "+i+": ["+a+"]","debug");j.write(e);return i},writeJS:function(a,e){var d=b.syncSafe;b.syncSafe=!0;var f=b.util.writeScript(a,!e);b.syncSafe=d;return f},writeScript:function(a,e,d){if(!b.syncSafe&&"undefined"==typeof b.safewriter)return b.util.log("ignoring unsafe attempt to document.write script [ "+a+" ]","warning"),!1;d&&"object"!==typeof d&&b.util.log("writeScript for "+a+"loadOptions should be an object [ "+d+" ]","error");var f="tmjs_"+
+b.util.elements++;b.util.log("writing "+f+": ["+a+"]","debug");var i='<script id="'+f+'"';e?i+=">"+a:(d&&d.defer&&(i+=' defer="defer"'),i+=' src="'+a+'">');i+="<\/script>";if(d&&d.onLoad&&!e){var p="var _oSS = TMAN.syncSafe; TMAN.syncSafe=true; TMAN.load.onLoadById('"+f+"', true); TMAN.syncSafe = _oSS";d.url=a;d.id=f;b.load.start(d)}j.write(i);p&&b.hack.addDelayedWrite(p)},writeIframe:function(a,e,d){if(!b.syncSafe)return b.util.log("ignoring attempt to document.write iframe ["+a+"] after dom ready",
"error"),!1;var f="tmif_"+b.util.elements++,e='<iframe id="'+f+'" src="'+a+'" style="position:absolute;top:0;left:-999em" '+(e?'width="18px" height="18px"':'width="0" height="0"');d?(e+=" onload=\"TMAN.load.onLoadById('"+f+"', true);\" onerror=\"TMAN.load.onLoadById('"+f+"', false);\">",d.url=a,d.id=f,b.load.start(d)):e+=">";b.util.log("writing "+f+": ["+a+"]","debug");j.write(e+"</iframe>");return f},parseKeyValue:function(a,e,d,f){var e=RegExp("([^=]+?)=([^"+e+"]*?)(?:"+e+"\\s*|$)","g"),i={},p,
f=d?f||b.util.decode:b.util.K;for("?"===a.charAt(0)&&(a=a.slice(1));p=e.exec(a);)d=f(p[1]),p=f(p[2]),i[d]?("string"===typeof i[d]&&(i[d]=[i[d]]),i[d].push(p)):i[d]=p;return i},setKeyValue:function(a,e,d,f,i,p){p=i?p||b.util.encode:b.util.K;d=p(e)+"="+p(d);a=a.replace(RegExp("(^|"+f+"\\s*|\\?)"+p(e)+"=[^"+f+"]*?("+f+"\\s*|$)","g"),function(a,e,b){return e+d+b});return 0>a.indexOf(d)?a+f+d:a},forEach:u,cookie:function(a,e,d){if((a+e).length>b.MAX_COOKIE_LENGTH){if(a.length>b.MAX_COOKIE_LENGTH)return b.util.log("key exceeds "+
b.MAX_COOKIE_LENGTH+" chars, unable to set: "+a,"warning"),!1;b.util.log("attempt to set/get cookie "+a+"beyond"+b.MAX_COOKIE_LENGTH+" chars"+e,"warning");e=e.substr(0,b.MAX_COOKIE_LENGTH-a.length)}if(1<arguments.length&&(null===e||"object"!==typeof e)){d=b.util.extend({},d);null===e&&(d.expires=-1);if("number"===typeof d.expires){var f=d.expires,i=d.expires=new Date;i.setDate(i.getDate()+f)}return j.cookie=[encodeURIComponent(a),"=",d.raw?String(e):encodeURIComponent(String(e)),d.expires?"; expires="+
d.expires.toUTCString():"",d.path?"; path="+d.path:"",d.domain?"; domain="+d.domain:"",d.secure?"; secure":""].join("")}d=e||{};i=d.raw?function(a){return a}:decodeURIComponent;return(f=RegExp("(?:^|; )"+encodeURIComponent(a)+"=([^;]*)").exec(j.cookie))?i(f[1]):null},scramble:function(a){if(null==a)return null;if(0==a.length)return a;for(var e=[1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],b="",f="4!\"#$1&'()*+,-./0123456789:2<3>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}".split(b),i=a.length,g=0;g<i;g++){var h=(a.charAt(g).charCodeAt(0)+g+62)%94;e[h]&&(b+="%");b+=f[h]}return b},unscramble:function(a){if(null==a)return null;if(0==a.length)return a;for(var e=0,b="",f=a.length,i=0,g;i<f;i++){g=a.charAt(i);if("%"==g)if(i++,g=a.charAt(i),"4"==g)g=" ";else if("3"==g)g="=";else if("2"==g)g=";";else if("1"==g)g="%";else{i--;continue}b+=
String.fromCharCode((156+g.charCodeAt(0)-e++%94)%94+32)}return b},loadScriptOnce:function(a,e,d){e=e||{};if(b.load.isLoadedByURL(a)){if("function"===typeof e.onLoad)e.onLoad(!0);return!0}if(b.load.isLoadingByURL(a)){if("function"===typeof e.onLoad||"function"===typeof e.onError)a=b.load.getElementHandlerByURL(a),"function"===typeof e.onLoad&&a._addOnLoad(e.onLoad);return!1}if(b.load.isDeadByURL(a)&&"function"===typeof e.error)return e.onError(),!1;e.url=a;d?(b.client.useDelayedWrite(),b.util.writeScript(a,
!1,e)):b.util.appendScript(a,!1,e)},isBody:function(){return j.body||j.getElementsByTagName("head")[0]},preCacheScript:function(a,e){e=e||{};if(b.load.isLoadedByURL(a)){if("function"===typeof e.onLoad)e.onLoad(!0);return!0}if(b.load.isLoadingByURL(a)){var d=b.load.getElementHandlerByURL(a);"function"===typeof e.onLoad&&d._addOnLoad(e.onLoad);return!1}if(b.load.isDeadByURL(a)||"function"!==typeof b.client.preCacheType||!b.util.isBody()&&!b.client.canHeadPrecache)return!1;e.url=a;e.errorOK=!0;return b.util["append"+
("object"===b.client.preCacheType()?"Object":"Image")](a,e)},arrayIndexOf:function(a,e){if("object"===typeof a&&a.length){if("function"===typeof a.indexOf)return a.indexOf(e);for(var b=a.length;b--;)if(a[b]===e)return b}return-1}}}b.getUID=function(){b.uid||(b.uid=b.util.getUID());return b.uid};this.TMAN||(this.TMAN={});if(!b.date){var C=function(a,e){var b=new Date,f=e?"getUTC":"get",b=new Date(b[f+"FullYear"](),b[f+"Month"](),b[f+"Date"]()+(a||0));return e?new Date(b-6E4*b.getTimezoneOffset()):
b};b.date={today:function(a){return C(a)},todayUTC:function(a){return C(a,!0)}}}this.JSON||(JSON={});(function(){function a(a){return 10>a?"0"+a:a}function b(a){i.lastIndex=0;return i.test(a)?'"'+a.replace(i,function(a){var b=j[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function d(a,f){var i,h,j,m,o=g,n,s=f[a];s&&("object"===typeof s&&"function"===typeof s.toJSON)&&(s=s.toJSON(a));"function"===typeof k&&(s=k.call(f,a,s));switch(typeof s){case "string":return b(s);
case "number":return isFinite(s)?String(s):"null";case "boolean":case "null":return String(s);case "object":if(!s)return"null";g+=l;n=[];if("[object Array]"===Object.prototype.toString.apply(s)){m=s.length;for(i=0;i<m;i+=1)n[i]=d(i,s)||"null";j=0===n.length?"[]":g?"[\n"+g+n.join(",\n"+g)+"\n"+o+"]":"["+n.join(",")+"]";g=o;return j}if(k&&"object"===typeof k){m=k.length;for(i=0;i<m;i+=1)"string"===typeof k[i]&&(h=k[i],(j=d(h,s))&&n.push(b(h)+(g?": ":":")+j))}else for(h in s)Object.prototype.hasOwnProperty.call(s,
h)&&(j=d(h,s))&&n.push(b(h)+(g?": ":":")+j);j=0===n.length?"{}":g?"{\n"+g+n.join(",\n"+g)+"\n"+o+"}":"{"+n.join(",")+"}";g=o;return j}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});
var f=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,i=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g,l,j={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},k;"function"!==typeof JSON.stringify&&(JSON.stringify=function(a,b,e){var f;l=g="";if(typeof e==="number")for(f=0;f<e;f=f+1)l=l+" ";else typeof e==="string"&&(l=e);if((k=b)&&typeof b!==
"function"&&(typeof b!=="object"||typeof b.length!=="number"))throw Error("JSON.stringify");return d("",{"":a})});"function"!==typeof JSON.parse&&(JSON.parse=function(a,b){function e(a,d){var f,i,g=a[d];if(g&&typeof g==="object")for(f in g)if(Object.prototype.hasOwnProperty.call(g,f)){i=e(g,f);i!==h?g[f]=i:delete g[f]}return b.call(a,d,g)}var d,a=String(a);f.lastIndex=0;f.test(a)&&(a=a.replace(f,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){d=eval("("+a+")");return typeof b==="function"?e({"":d},""):d}throw new SyntaxError("JSON.parse");})})();b.POLL_INTERVAL||(b.POLL_INTERVAL=100);b.ElementHandler=function(a){if(!a||!a.url||!a.id)return b.util.log("ElementHandler expects url & id options","Error"),!1;this.url=a.url;this.elementId=a.id;this.element=a.element;var e=this;this.startTime=+new Date;this.timeOut=a.timeOut||
!1;this.tag=a.tag||h;this.timeOut&&this._addShouldKill(function(){return e.getTime()>=e.timeOut});"function"==typeof a.shouldKill&&this._addShouldKill(a.shouldKill);"function"==typeof a.onLoad&&this._addOnLoad(a.onLoad);this.shouldPoll()&&b.load.startPolling()};b.ElementHandler.prototype={_finish:function(a){this.endTime||(this.endTime=+new Date,this.loaded=a||!1,"function"===typeof this._onLoad&&this._onLoad(a),this._shouldKill=!1,b.load.finishedLoading(this))},shouldPoll:function(){return"function"==
typeof this._shouldKill||b.client.useReadyState()},poll:function(){if(!this.element&&this.elementId)try{this.element=j.getElementById(this.elementId)}catch(a){}this.element&&b.client.useReadyState()&&this.element.readyState&&("loading"!=this.element.readyState&&"uninitialized"!==this.element.readyState)&&this._finish("complete"==this.element.readyState||"loaded"==this.element.readyState);!this.endTime&&("function"==typeof this._shouldKill&&this._shouldKill())&&this.kill()},getTime:function(){return(this.endTime||
+new Date)-this.startTime},_shouldKill:!1,kill:function(){this.endTime||(b.util.killById(this.elementId),this.shouldKill=!1,this._finish(!1))},_addOnLoad:function(a){"function"!==typeof a&&b.util.log("_addOnLoad requires function received "+typeof a);if(this._onLoad){var e=this._onLoad;this._onLoad=function(b){e(b);a.call(this,b)};return!0}this._onLoad=a},_addShouldKill:function(a){if("function"==typeof this._shouldKill){var b=this._shouldKill;this._shouldKill=function(){return b.call(this)||a.call(this)}}else this._shouldKill=
a}};var ja=function(a){for(var e=D.slice(),d=e.length,f=!1;d&&d--;)e[d].poll(),f=!0;!a&&!f&&b.load.stopPolling();return f},Q=function(a,e,d){if("object"!=typeof e){if("object"==typeof D&&"object"==typeof E)return Q(a,D,d)||Q(a,E,d);b.util.logError("TNAN.load._done,_queue are not arrays","fatal");return!1}for(var f=e.length;f&f--;)if(a&&e[f].url==a||d&&e[f].elementId==d)return e[f];return!1},D=[],E=[],R=!1,N=!1;b.load={start:function(a){if(!a)return!1;a=new b.ElementHandler(a);D.push(a);return a},
startPolling:function(){N||(R=setInterval(ja,b.POLL_INTERVAL),N=!0);return!0},stopPolling:function(){if(N){for(var a=D.length;a--;)if(D[a].shouldPoll())return!1;N=!1;R=!!clearInterval(R)}return!0},isPolling:function(){return!1!==R},getElementHandlerByURL:function(a,b){return Q(a,b,!1)},getElementHandlerById:function(a,b){return Q(0,b,a)},finishedLoading:function(a){a||b.util.log("loadElement not supplied to finishedLoading","error");E.push(a);D.splice(b.util.arrayIndexOf(D,a),1);N&&b.load.stopPolling()},
isLoadingByURL:function(a){b.load.poll(!0);return b.load.getElementHandlerByURL(a,D)?!0:!1},isLoadedByURL:function(a){b.load.poll(!0);return(a=b.load.getElementHandlerByURL(a,E))?a.loaded:!1},getLoadTimeByURL:function(a){return(a=b.load.getElementHandlerByURL(a,E))?a.getTime():!1},getLoadTimeById:function(a){return(a=b.load.getElementHandlerById(a,E))?a.getTime():!1},isDeadByURL:function(a){return(a=b.load.getElementHandlerByURL(a,E))?!a.loaded:!1},isDeadById:function(a){return(a=b.load.getElementHandlerById(0,
E,a))?!a.loaded:!1},isLoadingById:function(a){b.load.poll(!0);return b.load.getElementHandlerById(a,D)?!0:!1},isLoadedById:function(a){b.load.poll(!0);return(a=b.load.getElementHandlerById(a,E))&&a.loaded||!1},onLoadById:function(a,e){var d=b.load.getElementHandlerById(a);return d?(d._finish(e),!0):!1},onLoadByURL:function(a,e){var d=b.load.getElementHandlerByURL(a);return d?(d._finish(e),!0):!1},onLoad:function(a){if(this===g)return b.util.log("onLoad expects to be called in element context, use call(this,success)",
"error"),!1;this.tagman.handle.endTime||this.tagman.handle._finish(a||this.tagman.errorOK)},reset:function(){D=[];E=[];b.load.stopPolling()},poll:ja};b.remoteLogURL=("file:"===location.protocol?"http:":"")+"//stats.tagman.com/";b.isTimedOut=b.isTimedOut||function(){return!1};b.Log=function(a){this._options=a||(a={});var e=a.logRate||{},d,f=this._messageTypes.length;this._history=[];for(this._doLogging={};f--;)d=this._messageTypes[f],this._doLogging[d]=this._level(e[d]);this._throwErrors=a.throwErrors||
{};e=a.statRate||{};this._doStats={};for(f=this._statTypes.length;f--;)d=this._statTypes[f],this._doStats[d]=this._level(e[d]);this._logContainerStart=a.quietMode?!1:!0;this.writeRemotely();b.util.cookie("tmDebug")&&this.setDebugMode()};b.Log.prototype={_messageTypes:["debug","info","warning","error","fatal"],_statTypes:["tag","container","parameter"],_level:function(a){a=a||0;return{sampleRate:a,display:a?100===a?!0:b.num.doSample(a)?!0:!1:!1}},displayOut:(null!==b.util.cookie("tmDebug")||"127.0.0.1"===
location.host)&&"object"===typeof console&&console.log,setLogLevelRate:function(a,b){"undefined"===typeof a||"undefined"===typeof b?this.error("level and rate must be defined","error"):this._doLogging[a]=this._level(b)},setStatTypeRate:function(a,b){"undefined"===typeof a||"undefined"===typeof b?this.error("type and rate must be defined","error"):this._doStats[a]=this._level(b)},writeRemotely:function(){var a,e;for(a in this._doStats)if(this._doStats[a].sampleRate){e=!0;break}this.writeRemotely=!(!b.remoteLogURL||
!e)},getLogging:function(a){return this._doLogging[a.toLowerCase()].display},getLogRate:function(a){return this._doLogging[a.toLowerCase()].sampleRate},getStats:function(a){return this._doStats[a.toLowerCase()].display},getStatsRate:function(a){return a&&(a=a.toLowerCase())in this._doStats?this._doStats[a].sampleRate:0},setDebugMode:function(){for(var a,b=this._messageTypes.length;b--;)a=this._messageTypes[b],this._doLogging[a]=this._level(100);this.displayOut="undefined"!==typeof console&&console.log?
!0:!1;this.writeRemotely=!1;return!0},_write:function(a,e){var e=e?e.toLowerCase():this._messageTypes[0],d="TagMan("+e+"):[ "+a+" ]";this.getLogging(e)&&(this.displayOut&&this.display(d),this.writeRemotely&&this.remoteWrite({lv:b.util.arrayIndexOf(this._messageTypes,e),me:a,sr:this.getLogRate(e)},"lm"));this._history.push(d);return d},display:function(a){this.displayOut&&console.log(decodeURIComponent(a))},remoteWrite:function(a,e){if(!this.writeRemotely||!a)return!1;this.containerStart();a.id=a.id||
b.uid;a.ac=a.ac||this.container.account;a.po="undefined"!==typeof a.po?a.po:b.currentPosition;var d=b.remoteLogURL+e+"?"+b.String.objectToQuery(a);b.util.appendImage(d);return d},message:function(a,b){this._write(a,b)},error:function(a,b){var d=this._write(a,b);if(this._throwErrors[b.toLowerCase()])throw Error(d);},containerStart:function(a){if(!this._logContainerStart)return!1;this._logContainerStart=!1;for(var a=a||this._options||{},e=0,d=0,f;f=this._statTypes[d++];)e=Math.max(e,this.getStatsRate(f));
a={rf:a.rf||location.href,sp:a.sp||b.currentPosition,as:a.as||this.container.async?1:0,bi:a.bi||this.container.baseId,ci:a.ci||this.container.id,br:a.br||b.client.getBrowser(),os:a.os||b.client.getOS(),sr:a.sr||e,lp:a.lp||this.container.isLandingPageDisabled()?1:0};this.writeRemotely?this.display(this.remoteWrite(a,"cs").substr(b.remoteLogURL.length)):this.display(b.String.objectToQuery(a));return!0},tagEnd:function(a){a&&!(a instanceof b.Tag)&&(a=this.container.getTagById(a));!a instanceof b.Tag&&
this.error("tagEnd required a TMAN.Tag or valid Id");this.getStats("tag")&&(a={ti:a.id,tb:a.getLoadTime(),tl:b.isTimedOut()?"p":this.container.isTimedOut()?"c":a.isTimedOut()?"t":a.isRunOnceActive()?"r":h,sr:this.getStatsRate("tag")},this.writeRemotely?this.display(this.remoteWrite(a,"te").substr(b.remoteLogURL.length)):this.display(b.String.objectToQuery(a)))},containerEnd:function(a){for(var a=a||{},e="",d="",f=this.container.tags.length,i;f--;)i=this.container.tags[f],i.hasExecuted()?e+=","+i.id:
d+=","+i.id;a={sr:a.sr||this.getStatsRate("container"),tl:a.tl||e.substr(1),tk:a.tk||d.substr(1),bt:a.cb||b.blockingTime,tp:a.tp||b.getPageLoadTime(),bc:a.bc||this.container.blockCalls,wl:a.wl||b.waitLatency||h};this.writeRemotely?this.display(this.remoteWrite(a,"ce").substr(b.remoteLogURL.length)):this.display(b.String.objectToQuery(a))},containerParams:function(){var a={},e;for(e in this.container.param)a[e]=this.container.param[e];a.sr=this.getStatsRate("container");this.writeRemotely?this.display(this.remoteWrite(a,
"cp")):this.display(b.String.objectToQuery(a));return!1},getHistory:function(){return this._history}};t=b;u=function(a){return{get:function(b,d){var f=a.getItem(H+b);return!f?null:(f=S(f.toString()),f.expiry<=new Date)?this.remove(b):f[d?Z:$]},set:function(b,d,f){if(null===d)return this.remove(b);a.setItem(H+b,T({expiry:aa(f||J),data:d}));return d},remove:function(b){a.removeItem(H+b);return null},clear:function(){for(var b=0,d=RegExp("^"+H),f;b<a.length;)d.test(f=a.key(b))?a.removeItem(f):b++}}};
var aa=function(a){return"number"==typeof a?(new Date).getTime()+1E3*(a|0):a instanceof Date?a.getTime():(new Date).getTime()+1E3*J},I,H="__test",J=1800,ba,ca=["localStorage","globalStorage","userData","cookies"],U=0,n,v,ka=location.hostname,Z="expiry",$="data",S=JSON.parse,T=JSON.stringify,K={get:function(a,b){return I.get(a,b)},set:function(a,b,d){return I.set(a,b,d)},remove:function(a){return I.remove(a)},clear:function(){return I.clear()},getExpiry:function(a){return!arguments.length?J:I.get(a,
!0)},setExpiry:function(a,b){var d;if(2===arguments.length)return null!==(d=this.get(a))?this.set(a,d,b):d;1===arguments.length&&(J=K._expiry=a|0)},store:function(a,b,d){if(null===b)return this.remove(a);if(1==arguments.length)return this.get(a);if(1<arguments.length)return this.set(a,b,d)},setType:function(a){var b=ca.join(",");return a&&-1<b.indexOf(a)&&a in K&&ba!=a?(I=K[this._type=ba=a],I.init&&I.init(),!0):!1},getType:function(){return ba},_prefix:H,_expiry:J,cookies:{get:function(a,b){var d=
j.cookie.match(RegExp("(?:^|; )"+H+a+"=([^;]+)"));return d&&S(decodeURIComponent(d[1]))[b?Z:$]||null},set:function(a,b,d){null===b&&(d=-1E9);d=aa(d||J);a=[H+a+"="+encodeURIComponent(T({expiry:d,data:b})),"path=/"];a.push("expires="+(new Date(d)).toUTCString());j.cookie=a.join("; ");return b},remove:function(a){return this.set(a,null)},clear:function(){for(var a=j.cookie.split(";"),b,d=0,f=RegExp("(?:^| )"+H+"([^ =;]+)=([^;]+)");b=a[d++];)(b=b.match(f))&&this.remove(b[1])}}};for(;2>U&&(n=ca[U++]);)try{v=
"globalStorage"==n?g[n][ka+(0>ka.indexOf(".")?".localdomain":"")]:g[n],v.getItem&&(v.setItem&&v.removeItem)&&(K[n]=u(v))}catch(xa){}if(j.documentElement.addBehavior){var y,M,da=function(a){return a.replace(/[^0-9a-zA-Z-_.]+/g,"-")},V=function(){y.setAttribute("tman-keys",T(M));y.save("tman-keys")};K.userData={init:function(){var a=j.head||j.getElementsByTagName("head")[0]||j.documentElement;y=this._element=j.createElement("div");y.addBehavior("#default#userdata");y.style.display="none";a.insertBefore(y,
a.firstChild);y.load("tman-keys");M=(a=y.getAttribute("tman-keys"))&&S(a)||{}},set:function(a,b,d){if(null===b)return this.remove(a);y.setAttribute(a=da(a),T({expiry:aa(d||J),data:b}));M[a]=1;V();return b},get:function(a,b){var d=y.getAttribute(a=da(a));return!d?null:(d=S(d),d.expiry<=new Date)?this.remove(a):d[b?Z:$]},remove:function(a){y.removeAttribute(a=da(a));delete M[a];V();return null},clear:function(a){for(a in M)y.removeAttribute(a),delete M[a];V()},save:V,_suffix:""}}for(U=0;(n=ca[U++])&&
!K.setType(n););B=t.storage=K;b.Session=function(a,b,d){if("string"!==typeof a)throw Error("account must be a string");this.account=a;a=+new Date;this.initTime="undefined"!==typeof d?d:a;this.timeout="undefined"!==typeof b?b:1800};b.Session.prototype={isActive:function(){return"boolean"===typeof this._isActive?this._isActive:this._isActive=!this.isNewSession()},_setLastActive:function(){var a="TMLA_"+this.account;this._nowInSecs=Math.floor(this.initTime/1E3);this._lastActive=B.get(a);B.set(a,this._nowInSecs)},
isNewSession:function(){this._setLastActive();return!this._lastActive||this._nowInSecs-this._lastActive>this.timeout?!0:!1}};b.String||(b.String=function(a){this.value=a},b.String.prototype={replaceIfMatch:function(a,b){var d=this.value.match(a);if(!d)return this.value="",this;d=d[0];if(!b)return this.value=d,this;this.value=d.replace(a,b);return this},replace:function(a,b){this.value=this.value.replace(a,b);return this},toString:function(){return this.value},callIfMatch:function(a){for(var b=1,d=
arguments.length;b<d;b++)if(this.value.match(arguments[b]))return a()}},b.String.escape=function(a){return escape(a).replace(/\//g,"%2F")},b.String.doubleEscape=function(a,e){var d=b.String.escape(b.String.escape(a));return e?d.replace(RegExp("^(.{1,"+e+"})(?:%25.*|$)"),"$1"):d},b.String.getHostname=function(a){var b=a.indexOf("//"),d,b=-1<b?b+2:0;d=a.indexOf("/",b);return a.substring(b,d)},b.String.getParam=function(a,e){return a&&e&&b.util.parseKeyValue(a,"&",!1)[e]},b.String.getProtocol=function(a){var b=
a.indexOf("//");return-1<b?a.substring(0,b):""},b.String.getQueryParam=function(a,b){if(!b)return"";for(var d=b+"=",f=0;-1<(f=a.indexOf(d,f));){if(0===f||"&"===a.charAt(f-1))return f+=d.length,d=a.indexOf("&",f),0>d&&(d=a.length),a=a.substring(f,d),decodeURIComponent(a);f+=d.length}return""},b.String.getQueryString=function(a){var b=a.indexOf("?");if(-1<b){var d=a.indexOf("#");if(-1===d)return a.substring(b+1);if(b<d)return a.substring(b+1,d)}return""},b.String.getURLFragment=function(a){var b=a.indexOf("#");
return-1<b?a.substring(b+1):""},b.String.setParam=function(a,e,d){var f=b.util.parseKeyValue(a||"?","&",!1);f[e]=d;return("?"===a.charAt(0)?"?":"")+b.String.objectToQuery(f)},b.String.objectToQuery=function(a){"object"!=typeof a&&b.util.log("objectToQuery not passed object: "+a,"debug");var e=[],d;for(d in a)e.push("&",encodeURIComponent(d),"=",encodeURIComponent(a[d]));return e.slice(1).join("")},b.String.queryToObject=function(a){return b.util.parseKeyValue(a||"?","&",!0)},b.String.subString=function(a,
b,d){var f="".substr;return d?f.call(a||"",b,d):f.call(a||"",b)},b.String.regEx=function(a,b){if(a&&b){var d=RegExp(b).exec(a);if(d)return d.splice(0,1),d.join("")}return""},b.String.isFound=function(a,b){return a&&b?-1==a.indexOf(b)?0:1:0},b.String.printR=function(a,e){var d=[],f=Array(e?++e:e=1).join("\t");if(null==a)d.push(f,null===a?"null":"undefined","<br>");else switch(typeof a){case "function":case "string":a=(""+a).replace(/</g,"&lt;").replace(/(\r\n|\n|\r)/g,"$1"+f);case "boolean":case "number":d.push(f,
a,"<br>");break;default:if(a.length){d.push(f,"ArrayObject<br>");for(var i=0,g=a.length;i<g;++i)d.push(f,"[",i,"] ",b.String.printR(a[i],e).toString().replace(/^\s+/,""),"<br>")}else for(i in d.push(f,a.name||"Generic"," Object<br>"),a)d.push(f,"['",i,"'] ",b.String.printR(a[i],e).toString().replace(/^\s+/,""),"<br>")}return d.join("").replace(/<br><br>/g,"<br>")},b.String.getStem=function(a,b){if(a&&b){for(var d="",b=","+b+",",f=a.split("/"),i=-1*f.length,g=0;g<f.length;g+=1){if(-1<b.indexOf(","+
g+",")||-1<b.indexOf(","+i+","))d&&(d+="/"),d+=f[g];i+=1}return d}},b.String.trim=function(a){for(var a=a.replace(/^\s\s*/,""),b=/\s/,d=a.length;b.test(a.charAt(--d)););return a.slice(0,d+1)},b.String.checksum=function(a){for(var b=0,d=a.toString().length;d&&d--;)b+=a.charCodeAt(d)*(d+1);return b});"undefined"==typeof b&&(b={});n=function(){};var qa=Array.prototype.join;n.prototype={constructor:n,length:0,push:Array.prototype.push,append:Array.prototype.push,size:function(){return this.toString().length},
toString:function(){return qa.call(this,"")}};b.StringBuilder=n;b.num||(b.num={getCacheBuster:function(a){return(Math.random()+"").substr(2,a)},doSample:function(a){return(Math.random()*100<=(a||0))>>0},base26Encode:function(a){var b="";do{b=String.fromCharCode(a%26+65)+b;a=a/26-1}while(a>=0);return b},base26Decode:function(a){for(var b=a.length-1,d=1,f=a.charCodeAt(b)-65;--b>=0;){d=d*26;f=f+d*(a.charCodeAt(b)-64)}return f},base92encode:function(a,b){var d;if(!b){for(var f=0;Math.pow(92,f++)<a;);
b=f-1}typeof a!="array"&&(a=a.toString().split(""));d=a.length;for(var i=Array(d),f=Array(b),g=0,g=0;g<d;g++)i[g]=a[g];for(g=0;g<b;g++){var h=i;d=h.length;for(var i=Array(d*2),l=0,j=0,k=0,k=0;k<d*2;k++){l=l<<16;i[k]=k%2==0?h[j]>>16&65535|l:h[j++]&65535|l;l=i[k]%92;i[k]=i[k]/92|0}h=Array(d);for(k=0;k<d;k++)h[k]=i[k*2]<<16|i[k*2+1];d=l;i=h;f[g]=d}for(d="";b>0;){g=f[--b];d=g>58?d+String.fromCharCode(g+34):g>1?d+String.fromCharCode(g+33):d+String.fromCharCode(g+32)}return d}});n=function(a){if((a=ea(a))&&
a.innerHTML)try{Function(a.innerHTML)()}catch(b){LEVU.LE('Error in `evaluateScript`. Script contents: "'+a.innerHTML+'"',"Error")}};var ea=function(a){for(var b=j.getElementsByTagName("script"),d=b.length;d--;)if(b[d].src.indexOf("/"+a)>-1)return b[d];return""};v=function(a){var b=ea(a);if(b){var d=b.src.indexOf("/"+a+"?");if(d>-1)return b.src.substr(d+a.length+2)}return""};t=function(a,e,d){if(!b.syncSafe){b.util.log("Attempt to added delayed write when not syncSafe: "+a,"error");return false}if(a){typeof a===
"function"?a="("+a.toString()+")();":b.String.trim(a).substr(-1)!==";"&&(a=a+";");d&&d.onLoad&&(a=typeof d.onLoad==="function"?a+("("+d.onLoad.toString()+")();"):a+"loadOptions.onLoad;");if(b.client.useDelayedWrite()){e?L.unshift(a):L.push(a);b.util.log("Adding to "+(e?"start":"end")+" of delayed write queue of size ("+L.length+" inc) : "+a.toString(),"debug");fa()}else{if(!a){b.util.log("addDelayedWrite called without code argument","error");return}b.util.writeScript(a,true)}return true}b.util.log("addDelayedWrite called without code argument",
"error")};var fa=function(){if(L.length&&!ga){b.util.log("delayed write block "+la+" inserted","debug");var a=b.util.getProtocol(),e;if(a==="file://")a="http://127.0.0.1";else{e=a==="https://"?ra:sa;a=a+e}typeof LEVU=="undefined"?b.util.writeJS(a+"/js/TMAN.hack.WDW.js",1):b.util.writeJS(a+"/js/LEVU.WDW.xjs",1);ga=true}};u=function(){var a=b.syncSafe;b.syncSafe=true;ga=false;var e=L.length,d;if(L.length){d=L.shift();b.util.log("delayed write executing block "+la++ +" : "+d.toString(),"debug");var f=
b.syncSafe;b.syncSafe=true;typeof d==="function"?d():b.util.writeScript(d,true);b.syncSafe=f}e>1&&fa();b.syncSafe=a};var sa="res.levexis.com",ra="sec.levexis.com",L=[],ga=!1,la=1;b.hack||(b.hack={evalScript:n,findScript:ea,getScriptParams:v,addDelayedWrite:t,initDelayedWrite:fa,writeDelayedWrite:u,WDW:u});var ha,ma=function(){};ma.prototype={otag:"{{",ctag:"}}",pragmas:{},buffer:[],pragmas_implemented:{"IMPLICIT-ITERATOR":!0},context:{},render:function(a,b,d,f){if(!f){this.context=b;this.buffer=[]}if(this.includes("",
a)){a=this.render_pragmas(a);a=this.render_section(a,b,d);if(f)return this.render_tags(a,b,d,f);this.render_tags(a,b,d,f)}else{if(f)return a;this.send(a)}},send:function(a){a!=""&&this.buffer.push(a)},render_pragmas:function(a){if(!this.includes("%",a))return a;var b=this;return a.replace(RegExp(this.otag+"%([\\w-]+) ?([\\w]+=[\\w]+)?"+this.ctag),function(a,f,g){if(!b.pragmas_implemented[f])throw{message:"This implementation of mustache doesn't understand the '"+f+"' pragma"};b.pragmas[f]={};if(g){a=
g.split("=");b.pragmas[f][a[0]]=a[1]}return""})},render_partial:function(a,b,d){a=this.trim(a);if(!d||d[a]===h)throw{message:"unknown_partial '"+a+"'"};return typeof b[a]!="object"?this.render(d[a],b,d,true):this.render(d[a],b[a],d,true)},render_section:function(a,b,d){if(!this.includes("#",a)&&!this.includes("^",a))return a;var f=this;return a.replace(RegExp(this.otag+"(\\^|\\#)\\s*(.+)\\s*"+this.ctag+"\n*([\\s\\S]+?)"+this.otag+"\\/\\s*\\2\\s*"+this.ctag+"\\s*","mg"),function(a,g,h,l){a=f.find(h,
b);if(g=="^")return!a||f.is_array(a)&&a.length===0?f.render(l,b,d,true):"";if(g=="#")return f.is_array(a)?f.map(a,function(a){return f.render(l,f.create_context(a),d,true)}).join(""):f.is_object(a)?f.render(l,f.create_context(a),d,true):typeof a==="function"?a.call(b,l,function(a){return f.render(a,b,d,true)}):a?f.render(l,b,d,true):""})},render_tags:function(a,b,d,f){for(var g=this,h=function(){return RegExp(g.otag+"(=|!|>|\\{|%)?([^\\/#\\^]+?)\\1?"+g.ctag+"+","g")},l=h(),j=function(a,f,k){switch(f){case "!":return"";
case "=":g.set_delimiters(k);l=h();return"";case ">":return g.render_partial(k,b,d);case "{":return g.find(k,b);default:return g.escape(g.find(k,b))}},a=a.split("\n"),k=0;k<a.length;k++){a[k]=a[k].replace(l,j,this);f||this.send(a[k])}if(f)return a.join("\n")},set_delimiters:function(a){a=a.split(" ");this.otag=this.escape_regex(a[0]);this.ctag=this.escape_regex(a[1])},escape_regex:function(a){if(!arguments.callee.sRE)arguments.callee.sRE=RegExp("(\\/|\\.|\\*|\\+|\\?|\\||\\(|\\)|\\[|\\]|\\{|\\}|\\\\)",
"g");return a.replace(arguments.callee.sRE,"\\$1")},find:function(a,b){var a=this.trim(a),d;if(b[a]===false||b[a]===0||b[a])d=b[a];else if(this.context[a]===false||this.context[a]===0||this.context[a])d=this.context[a];return typeof d==="function"?d.apply(b):d!==h?d:""},includes:function(a,b){return b.indexOf(this.otag+a)!=-1},escape:function(a){a=String(a===null?"":a);return a.replace(/&(?!\w+;)|["'<>\\]/g,function(a){switch(a){case "&":return"&amp;";case "\\":return"\\\\";case '"':return"&quot;";
case "'":return"&#39;";case "<":return"&lt;";case ">":return"&gt;";default:return a}})},create_context:function(a){if(this.is_object(a))return a;var b=".";if(this.pragmas["IMPLICIT-ITERATOR"])b=this.pragmas["IMPLICIT-ITERATOR"].iterator;var d={};d[b]=a;return d},is_object:function(a){return a&&typeof a=="object"},is_array:function(a){return Object.prototype.toString.call(a)==="[object Array]"},trim:function(a){return a.replace(/^\s*|\s*$/g,"")},map:function(a,b){if(typeof a.map=="function")return a.map(b);
for(var d=[],f=a.length,g=0;g<f;g++)d.push(b(a[g]));return d}};ha={name:"mustache.js",version:"0.3.1-dev",to_html:function(a,b,d,f){var g=new ma;if(f)g.send=f;g.render(a,b,d);if(!f)return g.buffer.join("\n")}};this.TMAN=this.TMAN||{};n=b;if(!(v=b.onDomReady)){v=function(a){W?a():ia.push(a)};var O=function(){if(!W){W=true;if(b.conf&&b.conf.param)b.conf.param.tmdom=1;for(clearInterval(X);ia.length;)ia.shift()();if(typeof G.readyState!=="string")G.readyState="complete"}};t=function(){/^(?:loaded|complete)$/i.test(G.readyState)&&
O()};var W=!1,ia=[],G=j,X=0;v.isReady=function(){return W};switch(!0){case !!G.addEventListener:G.addEventListener("DOMContentLoaded",O,!1);g.addEventListener("load",O,!1);G.addEventListener("readystatechange",t,!1);break;case !!G.attachEvent:G.attachEvent("onreadystatechange",t,!1),g.attachEvent("onload",O,!1);case null==g.frameElement&&!+"\v1":X=setInterval(function(){try{G.documentElement.doScroll("left")}catch(a){return}O()},15)}X||(X=setInterval(t,b.POLL_INTERVAL||100));b.isDomReady=!1;v(function(){b.isDomReady=
true})}n.onDomReady=v;b.conf={host:"gslb.tagman.com",async:!1,tagsBlockingTimeout:!1,sessionTimeout:0,bootstrap:!0,enableJSCall:!0,campaign:!0,serverCall:"",landingPageContainer:!1,storageType:"cookie",version:3,cdn:"res.levexis.com",waitService:"wt.tagman.com",statRate:0,statPosition:32,tagAcceleration:!1,debugMode:!1,tags:{}};l.prototype={_setOptions:function(a){this._setOptionsFromDefault(["async","bootstrap","campaign","cdn","enableJSCall","host","landingPageContainer","serverCall","sessionTimeout",
"statPosition","statRate","storageType","tagsBlockingTimeout","version","waitService","tagAcceleration"],a,b.conf)},_setOptionsFromDefault:function(a,b,d){for(var f=0,g;g=a[f++];)this[g]=g in b?b[g]:d[g]},addTags:function(){Array.prototype.push.apply(this.tags,arguments);for(var a=0,e;e=arguments[a++];){e.account=this.account;e.container=this;if(e.requiredScripts.length&&e.async&&!e.executeRequiredScripts){this.log.error("async scripts must execute required scripts, setting flag for tag "+e.id+" to execute",
"warning");e.executeRequiredScripts=true}if(b._secure!==e.secure){e.setTimedOut("security");this.log.error("tag + "+e.id+" timed out as TMAN._secure ("+b._secure+") does not match tag.secure ("+e.secure+").","warning")}}},addParams:function(a){for(var b in a)this.param[b]=a[b]},getParams:function(){return this.param},getTagById:function(a){for(var b=this.tags.length;b--;)if(this.tags[b].id==a)return this.tags[b]},isTimedOut:function(){return this.tagsBlockingTimeout?b.blockingTime>=this.tagsBlockingTimeout:
false},isLandingPageDisabled:function(){return!(!this.landingPageContainer||!this.isActive())},_setSession:function(){this.session=new b.Session(this.account,this.sessionTimeout,this.initTime)},isActive:function(){return this.session.isActive()},_performServerCall:function(){return false},fetchTagDefinitions:function(a,e){b.tagLibrary.fetchTagDefinitions(this.account,a,e)},initTagsFromMapping:function(){b.tagLibrary.initTagsFromMapping(this.account)},getHighestTagId:function(){return b.tagLibrary.getHighestTagId(this.account)},
enableAcceleration:function(){this.tagAcceleration=true},disableAcceleration:function(){this.tagAcceleration=false}};b.Container=l;b._containers=[];b.account={};b.addContainer=function(a){arguments.length>2&&!(arguments[0]instanceof b.Container)&&(a=new b.Container(arguments[0],arguments[1],arguments[2]));if(!a instanceof b.Container){b.util.log("container not passed to addContainer","fatal");return false}if(b.getContainerByName(a.account)){b.util.log("container already exists for "+a.account,"fatal");
return false}b._containers.push(a);b.account[a.account]=b._containers[b._containers.length-1];a.initTime=+new Date;a.storageType==="cookie"&&B.setType("cookies");a._setSession();a.log.containerStart();if(a.campaign&&typeof b.Track==="function")a.track=new b.Track(a,a.options);if(typeof b.tm2initialise==="function"){b.tm2initialise(a);b.tm2initialise=null}else a.serverCall&&a._performServerCall();return true};b.addParams=function(a,e){if(!a&&e){b.util.log("TMAN.addParams requires a container,params",
"error");return false}b.getContainerByName(a).addParams(e)};b.getParams=function(a){if(!a){b.util.log("TMAN.getParams requires a container or container name","error");return false}typeof a==="string"&&(a=b.getContainerByName(a));if(!a){b.util.log("Container does not exist. Can't retrieve params for it.","error");return false}return a.param};b.failOrDefer=function(){return b._doTagsCallback?b.Tag.globals.HOW_FAIL:b.Tag.globals.HOW_DEFER};b.doTags=function(a,e,d){try{if(a===b.position.DOTAGS_TIMER)a=
b.position.WINDOW_LOADED;b._doTagsCallback=false;var f="undefined"!=typeof b.safewriter,d="hmm"===d;if(!d&&!f)b._doTagsCallback=true;b.currentPosition=a;b.syncSafe=typeof e=="boolean"?e?false:true:b.isDomReady?false:true;for(var e=0,g=b._containers.length;e<g;e++){var h=b._containers[e];if(h.isLandingPageDisabled())h.log.error("doTags("+a+") disabled due to landing page","info");else if(h.isTimedOut()){h.log.error("doTags("+a+") disabled due to container blocking timeout","info");b.currentPosition===
h.statPosition&&h.log.containerEnd()}else{b.currentPosition===h.statPosition&&h.log.containerEnd();var l=h.tags;b.util.log("running doTags"+(d?" CALLBACK":"")+" for "+h.account+" @ position "+b.position.makeName(a)+" (syncSafe = "+b.syncSafe+")","debug");for(var k=l.length;k&&k--;){var j=l[k];if(!j.hasExecuted()||j.repeatable){b.util.log("doTags looking at tag ("+j.id+")","debug");j.preloadResources();if(a<=b.position.WINDOW_LOADED)j.position<=a&&j.execute();else if(j.position==a){if(!j.movable){b.util.log("changing post-WINDOW_LOADED tag to movable ("+
j.id+")","debug");j.movable=true}(!j.repeatable||!d)&&j.execute()}}}}}if(b._doTagsCallback){var m="TMAN.doTags("+b.currentPosition+","+(b.syncSafe?"false":"true")+", 'hmm');";b.syncSafe?b.hack.addDelayedWrite(m):setTimeout(m,b.POLL_INTERVAL*2)}else b.syncSafe&&b.hack.addDelayedWrite("TMAN.syncSafe = false;");return true}catch(n){b.util.log("Exception in doTags: "+n,"error");return false}};b.getContainerByName=function(a){for(var e=b._containers.length;e--;)if(b._containers[e].account===a)return b._containers[e]};
b.getParam=function(a,e){if(arguments.length==0){b.util.log("TMAN.getParam requires name","error");return false}e=typeof e==="string"?b.getContainerByName(e):b._containers[0];if(!e instanceof b.Container){b.util.log("Container does not exist. Can't retrieve param for it.","error");return false}return(typeof e.param[a]==="function"?e.param[a]():e.param[a])||""};b.addParam=function(a,e){if(!b._containers||!b._containers[0]instanceof b.Container){b.util.log("no container to add ["+a+"] to","warning");
return false}var d={};d[a]=e;b._containers[0].addParams(d);return true};b.reset=function(){b._containers=[];b.uid=h;b.account={};b.load.reset();b.blockingTime=0;b.currentPosition=0};b.position={PRE_HEAD:0,TOP_HEAD:1,BOTTOM_HEAD:2,TOP_BODY:3,BOTTOM_BODY:31,DOM_COMPLETE:32,WINDOW_LOADED:33,END:64,DOTAGS_TIMER:1E3};b.position.getName=function(a){for(var e in b.position)if(b.position[e]==a)return e;return false};b.position.makeName=function(a){var e=b.position.getName(a);return!e?a:"TMAN_"+e};g.addEventListener?
g.addEventListener("load",k,!1):g.attachEvent&&g.attachEvent("onload",k);b.POLL_INTERVAL||(b.POLL_INTERVAL=100);b.Tag=function(a,e){if(arguments.length<1)b.util.log("`code` argument is required","error");else{for(var d in e)typeof b.Tag.conf[d]=="undefined"&&b.util.log("Invalid property passed to Tag constructor: "+d,"warning");e||(e={});this.id=e.id||b.getTagId();this.code=a;this.position=typeof e.position!=="undefined"?e.position:0;this.target="target"in e?e.target:null;this.async="async"in e?e.async:
false;this.movable="movable"in e?e.movable:true;this.repeatable=e.repeatable&&this.position>b.position.WINDOW_LOADED||b.Tag.conf.repeatable;this.reference=e.reference;this.bootstrapper=e.bootstrapper||b.Tag.conf.bootstrapper;this.canExecute=typeof e.canExecute==="undefined"?r:typeof e.canExecute==="function"?e.canExecute:function(){return e.canExecute};this.timeout=typeof e.timeout!="undefined"?e.timeout:0;this.pageLoadTimeout=e.pageLoadTimeout||false;if(typeof e.secure=="undefined")this.secure=location.protocol==
"https:";else if(typeof e.secure!="boolean"){b.util.log("TAG.secure should be a boolean for id "+this.id,"error");this.secure=e.secure=="false"?false:true}else this.secure=e.secure;if("runOnce"in e)this.runOnce=typeof e.runOnce==="number"?new Date+e.runOnce*1E3:b.date.today(1);this.executeRequiredScripts="executeRequiredScripts"in e?e.executeRequiredScripts:false;this.requiredScripts=e.requiredScripts?typeof e.requiredScripts!=="object"?[e.requiredScripts]:e.requiredScripts:[];this._requiredScriptsLoadResults=
{};this._hasExecuted=false;this._executedAt=0;this._loaded=false}};b.Tag.globals={HOW_FAIL:!1,HOW_DEFER:!0,HOW_APPEND:"ap",HOW_DOCWRITE:"dw",HOW_SAFEWRITE:"sw"};b.Tag.conf={id:1,async:!1,requiredScripts:"",executeRequiredScripts:!1,timeout:0,pageLoadTimeout:!1,canExecute:function(){return true},runOnce:b.date.today(1),secure:"auto detect",reference:"",position:"",target:null,movable:"",repeatable:!1,bootstrapper:!1};var ta=0;b.getTagId=function(){return b.num.base26Encode(ta++)};b.Tag.prototype={setExecutedAt:function(a){if(!this._hasExecuted||
this.repeatable){this._executedAt=a;this._hasExecuted=true}else this.logError('setExecutedAt called with "'+a+'" but status was already '+this._executedAt+" (id: "+this.id+")","debug")},getExecutedAt:function(){return this._executedAt},hasExecuted:function(){return this._hasExecuted},logError:function(a,e){if(this.container&&this.container.log)this.container.log.error(a,e);else if(b.util&&b.util.log)b.util.log(a,e);else return false;return true},determineHowAndWhere:function(){var a=where=null;if(this.target){where=
b.util.findById(this.target);if(!where){this.logError("target of "+this.target+" not found, cannot execute (id: "+this.id+")","debug");return b.Tag.globals.HOW_FAIL}}a=b.position.makeName(this.position);if(b.util.findById(a)==null&&!this.movable&&(this.position==b.position.DOM_COMPLETE||this.position==b.position.WINDOW_LOADED))a=b.position.makeName(b.position.BOTTOM_BODY);var e="undefined"!=typeof b.safewriter;if(this.async)if(this.target)a=b.Tag.globals.HOW_APPEND;else if(b.syncSafe)if(this.movable){where=
j.getElementsByTagName("SCRIPT")[0].parentNode;a=b.Tag.globals.HOW_APPEND}else if(this.position==b.currentPosition)a=b.Tag.globals.HOW_DOCWRITE;else{where=b.util.findById(a);if(!where){this.logError("no element with id "+a+", cannot execute (id: "+this.id+")","debug");return b.failOrDefer()}a=b.Tag.globals.HOW_APPEND}else{if(this.movable)where=j.getElementsByTagName("SCRIPT")[0].parentNode;else{where=b.util.findById(a);if(!where){this.logError("no element with id "+a+", cannot execute (id: "+this.id+
")","debug");return b.failOrDefer()}}a=b.Tag.globals.HOW_APPEND}else if(b.syncSafe){if(this.target||!this.movable&&this.position!=b.currentPosition){if(e){this.logError("deferring execution until DOM_COMPLETE then safewrite (id: "+this.id+")","debug");return b.Tag.globals.HOW_DEFER}this.logError("safewriter unavailable to write retroactively, cannot execute (id: "+this.id+")","debug");return b.failOrDefer()}a=b.Tag.globals.HOW_DOCWRITE}else{if(this.bootstrapper)return b.Tag.globals.HOW_DEFER;if(e){if(!this.target)if(this.movable)where=
j.getElementsByTagName("SCRIPT")[0].parentNode;else{where=b.util.findById(a);if(!where){this.logError("no element with id "+a+", cannot execute (id: "+this.id+")","debug");return b.failOrDefer()}}a=b.Tag.globals.HOW_SAFEWRITE}else{this.logError("safewriter unavailable, cannot execute (id: "+this.id+")","debug");return b.failOrDefer()}}if(e&&b.Tag.globals.HOW_APPEND===a)a=b.Tag.globals.HOW_SAFEWRITE;return{how:a,where:where}},execute:function(){b.util.log("execute called for tag ("+this.id+") async="+
this.async+", movable="+this.movable+", position="+b.position.makeName(this.position)+", target="+this.target+", repeatable="+this.repeatable+", executed="+this.hasExecuted(),"debug");this.checkTimedOut("page");if(this.hasExecuted()&&!this.repeatable||this.isTimedOut()){this.logError("already executed or timedout (id: "+this.id+")","debug");return false}if(!this.async&&this.container.isTimedOut()){this.setTimedOut("container");this.logError("container timedout tag (id: "+this.id+")","debug");return false}var a=
this.determineHowAndWhere();if(a===b.Tag.globals.HOW_FAIL){this.setExecutedAt(-b.currentPosition);return false}if(a===b.Tag.globals.HOW_DEFER)return false;if(null===a){this.logError("determineHowAndWhere returned null, cannot execute (id: "+this.id+")","debug");this.setExecutedAt(-b.currentPosition);return false}if(!this.canExecute()){this.logError("canExecute condition not satisfied for tag (id: "+this.id+")","debug");return false}if(!this.isReadyToExecute()&&!this.async&&b.client.canWait()){if(this.timeout!==
0){this.logError("calling blockTag because our timeout="+this.timeout+" (id: "+this.id+")","debug");b.blockTag(this.id,this.account);return true}if(this.movable){this.logError("not ready to execute but movable so reattempt later (id: "+this.id+")","debug");return false}if(!b._doTagsCallback){this.logError("setting this tag as timed out (id: "+this.id+")","debug");this.setTimedOut("tag")}this.logError("tag waiting for required scripts so not ready to execute (id: "+this.id+")","debug");return true}if(this.isRunOnceActive())this.logError("runOnceActive says we've already run (id: "+
this.id+")","debug");else{this.starttimeoutTimer();switch(a.how){case b.Tag.globals.HOW_DOCWRITE:this.logError("injecting tag (id: "+this.id+")","debug");this._injectTag();break;case b.Tag.globals.HOW_APPEND:this.logError("injecting tag into "+a.where.tagName+"."+a.where.id+" (id: "+this.id+")","debug");this._injectTag(a.where);break;case b.Tag.globals.HOW_SAFEWRITE:this.logError("safewriting tag into "+a.where.tagName+"."+a.where.id+" (id: "+this.id+")","debug");this._safewriteTag(a.where);break;
default:this.logError('unexpected how "'+a.how+"\", won't execute (id: "+this.id+")","debug")}this.setExecutedAt(b.currentPosition);this.runOnce&&this.setRunOnceActive();this.async&&this.logFinished();return this.hasExecuted()}},logFinished:function(){var a=new Date;this._executionTime=this.startTime?a-this.startTime:0;this.logError(this.id+" end time "+a.getTime(),"debug");b.blockingTime=b.blockingTime+this._executionTime;this.container.log.tagEnd(this)},starttimeoutTimer:function(){if(this.timeout&&
!this._timedOut===h){var a=this;this._timedOut=false;this.logError("Starting timer of ("+this.timeout+"ms) for tag (id: "+this.id+")","debug");setTimeout(function(){this.hasExecuted()||(a.logError("Timer alarm and tag "+a.id+" not yet executed","debug")?true:false);a.setTimedOut()},this.timeout)}},setStartTime:function(){if(!("startTime"in this)){this.startTime=+new Date;this.logError(this.id+" start time "+this.startTime,"debug")}},_safewriteTag:function(a){b.safewriter.write(this.getCode(),a);return true},
_injectTag:function(a){if(this.async)return!!b.util.appendScript(this.getCode(),true,{tag:this,target:a,noOnload:true});a=this.getCode();this.startTime||(a="TMAN.getTag('"+this.id+"','"+this.container.account+"').setStartTime();"+a);b.String.trim(a).substr(-1)!=";"&&(a=a+";");a=a+"\n"+("TMAN.hack.addDelayedWrite( \"TMAN.getTag('"+this.id+"','"+this.container.account+"').logFinished();\",true);");b.hack.addDelayedWrite(a,true);return true},getCode:function(){var a=this.account;return this.code.replace(/\{\{(.*?)\}\}/g,
function(e,d){return b.getParam(d,a)})},checkTimedOut:function(){if(this._timedOut)return true;if(this.hasExecuted())return false;(!this.timeOutType||this.timeOutType=="page")&&this.pageLoadTimeout&&b.getPageLoadTime()>this.pageLoadTimeout?this.setTimedOut("page"):(!this.timeOutType||this.timeOutType=="tag")&&this.timeout!==false&&this.getElapsed()>this.timeout&&this.setTimedOut("tag");return this._timedOut||false},isTimedOut:function(){return this._timedOut||false},getElapsed:function(){if(!this.startTime)return 0;
if(!this.hasExecuted()&&!this._timedOut)this._executionTime=new Date-this.startTime;return this._executionTime},setTimedOut:function(a){this._timedOut=true;this._timeoutType=this._timeoutType||a||"tag";if(!this.hasExecuted()){this.logError("Tag "+this.id+" timed out ("+this._timeoutType+") after "+this.getElapsed()+"ms","warning");this.logFinished();b.load.poll(true)}},isReadyToExecute:function(){if(!this.async&&!b.client.canAccelerate(this.container)){this.requiredScripts.length&&b.util.log("tagAcceleration disabled ["+
this.id+"] always ready to execute");return true}for(var a=this.requiredScripts.length;a&&a--;)if(!this._requiredScriptsLoadResults[this.requiredScripts[a]])return false;return true},_getTagRunOnceUID:function(){return"TMRO_"+this.container.account+this.id},setRunOnceActive:function(){this.runOnce&&B.set(this._getTagrunOnceUID(),{LR:+new Date})},isRunOnceActive:function(){if(!this.runOnce)return false;var a=B.get(this._getTagRunOnceUID());return!a?false:new Date-a.LR<this.runOnce},preloadResources:function(){if(this.requiredScripts.length&&
!(this.startedPreload||!this.executeRequiredScripts&&(this.async||!b.client.canPrecache(b.currentPosition)))){this.startedPreload=true;for(var a=this.requiredScripts.length;a--;)this.preloadResource(this.requiredScripts[a])}},preloadResource:function(a){var e;this._requiredScriptsLoadResults[a]=false;if(this.executeRequiredScripts){this.logError("preloading ["+a+"] for tag "+this.id+" at pos "+b.currentPosition,"debug");e=b.util.loadScriptOnce;b.client.canAccelerate(this.container)||this.logError("preloading syncronously as tag acceleration disabled ( tag "+
this.id+" at pos )","info")}else{if(!b.client.canAccelerate(this.container)){this.logError("precaching disabled ["+a+"] for tag "+this.id+" at pos "+b.currentPosition,"info");return false}this.logError("precaching ["+a+"] for tag "+this.id+" at pos "+b.currentPosition,"debug");e=b.util.preCacheScript}e(a,{tag:this,onLoad:function(a){if(!(this instanceof b.ElementHandler))throw Error("onload call in wrong context");b.util.log("onload call for "+this.url+":"+this.tag.id+" (success: "+a+")");if(a){this.tag.logError("Loaded ["+
this.url+"] for tag "+this.tag.id,"debug");this.tag._requiredScriptsLoadResults[this.url]=true;(b.client.isExecSafeOnload()||this.tag.async)&&this.tag.execute()}},shouldKill:function(){return this.tag?this.tag.checkTimedOut():this.checkTimedOut()},onError:function(){return this.tag?this.tag.SetTimedOut("error"):this.SetTimedOut("error")}},!this.async&&(b.client.canAccelerate(this.container)||(this.position===b.currentPosition||this.position>b.currentPosition&&this.movable)&&this.timeout===false))},
isRequiredScriptLoaded:function(a){b.load.poll(true);return this._requiredScriptsLoadResults[a]?true:false},getLoadTime:function(){var a=+new Date-this.startTime;return isNaN(a)?0:a}};b._tags=[];b.onDomReady(function(){b.doTags(b.position.DOM_COMPLETE)});var ua=("https:"===j.location.protocol?"https":"http")+"://{{waitservice}}/wait/{{delay}}/0/{{uid}}_{{id}}",P=b.POLL_INTERVAL;b.blockTag=function(a,e,d){function f(){var e=new Date-j,f=P-b.waitLatency<0?0:P-b.waitLatency;b.waitLatency=e-f;d.logError("Blocked for "+
e+" v "+f+" adjusting offset to "+b.waitLatency+" tag("+a+")","debug");b._waiting=false}if(d=b.getTag(a,e)){d.isReadyToExecute()&&d.canExecute()&&d.execute();if(d.hasExecuted()||d.checkTimedOut()||!b.client.canWait())b._doTagsCallback=true;else{var g=P-b.waitLatency<0?0:P-b.waitLatency,h=ha.to_html(ua,{delay:g,uid:b.num.getCacheBuster(5),id:a,waitservice:d.container.waitService}),l=ha.to_html('(function () { TMAN.syncSafe=true; var Tag = TMAN.getTag(\'{{id}}\', "{{account}}"); if (!Tag.isReadyToExecute() && !Tag.checkTimedOut() ) { Tag.logError("blocking page for tag (id: {{id}}), elapsed " + Tag.getElapsed(),"debug");TMAN.blockTag(\'{{id}}\', "{{account}}");}else {Tag.logError("executing tag id: {{id}}","debug");TMAN.doTags(TMAN.currentPosition,false);TMAN.syncSafe=false;} })();',
{id:a,account:e}),j=+new Date;b.load.poll();if(b._waiting)d.logError("Not blocking for Tag + "+d.id+" due to TMAN._waiting. Tag will only be executed by doTags callback in this version which can cause issues with more than 2 accelerated tags at the same position","warning");else{d.starttimeoutTimer();d.setStartTime();if(d.container.blockCalls++>b.MAX_BLOCK_CALLS){b.getContainerByName(e).log.error("MAX_BLOCK_CALLS ("+d.container.MAX_BLOCK_CALLS+") reached for "+e+" whilst blocking for tag "+a,"fatal");
return false}d.logError("Blocking for tag ("+a+") with delayWithLatencyAdjusted: "+g+", elapsed "+d.getElapsed(),"debug");b._waiting=true;b.util.writeScript(h,false,{timeout:P,shouldKill:function(){return d.isTimedOut()},onLoad:f});b.hack.addDelayedWrite(l)}}}else b.util.log("Unable to find tag for blocking ("+a+","+e+")","error")};b.getTag=function(a,e){var d;d=e?b.getContainerByName(e):b._containers[0];if(!d||!(d instanceof b.Container)){b.util.log("Container "+e+" does not exist. Can't get tag.",
"error");return false}d=d.getTagById(a);if(!d||!(d instanceof b.Tag)){b.util.log("Tag (id: "+a+") does not exist on this container ("+e+").","error");return false}return d};b.getTagByReference=function(a,e){var d;d=e?b.getContainerByName(e):b._containers[0];if(!d||!(d instanceof b.Container)){b.util.log("Container "+e+" does not exist. Can't search tags.","error");return false}for(var f=d.tags.length;f&&f--;)if(d.tags[f].reference==a)return d.tags[f];return false};b.findTags=function(a,e){var a=a.toLowerCase(),
d,f=[];if(b._containers.length===0){b.util.log("No containers "+e+" found. Can't search tags.","info");return false}for(var g=b._containers.length;g&&g--;){d=b._containers[g];if(!e||e==d.account)for(var h=d.tags.length;h&&h--;)(d.tags[h].code+"###"+d.tags[h].requiredScripts.join("###").toLowerCase()).indexOf(a)>-1&&f.push(d.tags[h])}return f};b.tagsExecuted=function(a,e){var d=[];if(b._containers.length===0){b.util.log("No containers "+e+" found. Can't search tags.","info");return false}for(var f=
b._containers.length;f&&f--;){c=b._containers[f];if(!e||e==c.account)for(var g=c.tags.length;g&&g--;){var h=c.tags[g];((typeof a==="undefined"||a===true)&&h.getExecutedAt()>=0||a===false&&(!h.hasExecuted()||h.getExecutedAt()<0)||h.hasExecuted()&&h.getExecutedAt()===a)&&d.push(h)}}return d};b.addTag=function(a,e){if(e instanceof b.Tag){b.util.log("TMAN.addTag has changed, no longer accepts Tag","fatal");return false}var d=new b.Tag(a,e);if(d instanceof b.Tag){b.addTags(d);return true}return false};
b.addTags=function(){if(!b._containers||!(b._containers[0]instanceof b.Container)){b.util.log("no container to add tag to","warning");return false}return b.Container.prototype.addTags.apply(b._containers[0],arguments)};g.TMAN=g.TMAN||{};n=b;var na=function(a){q=h;var b=(a||navigator.userAgent).toLowerCase();if(b.indexOf("opera")>-1){if(a=b.match(/\bversion[\s\/](\d+\.\d+)/))q=a[1];else if(a=b.match(/\bopera[\s\/](\d+\.\d+)/))q=a[1];m="OP"}else if(b.indexOf("msie")!=-1){m="IE";if(a=b.match(/\bmsie (\d+\.\d+)/))q=
parseFloat(a[1])}else if(b.indexOf("firefox")!=-1){m="FF";if(a=b.match(/\bfirefox\/(\d+\.\d+)/))q=a[1]}else if(b.indexOf("chrome")>-1){m="CR";if(a=b.match(/\bchrome\/(\d+\.\d+)/))q=a[1]}else if(b.indexOf("safari 1.1.3")>-1||b.indexOf("safari/525.27.1")>-1||b.indexOf("applewebkit ")>-1){q="0.0";m="SF"}else if(b.indexOf("applewebkit")>-1){if((a=b.match(/\bversion\/(\d+\.\d+)/))&&b.indexOf("safari/534.8")==-1)q=a[1];else if(a=b.match(/\bapplewebkit\/(\d+\.?\d+)/)){b={419:"2.0","418.9":"2.0","418.8":"2.0",
418:"2.0","417.9":"2.0","416.11":"2.0","416.12":"2.0","412.17":"2.0","412.6":"2.0",412:"2.0","312.8":"1.3","312.5":"1.3","312.1":"1.3","125.4":"1.2","125.5":"1.2","125.2":"1.2",124:"1.2","85.8":"1.0","85.7":"1.0"};q=typeof b[a[1]]!="undefined"?b[a[1]]:"0.0"}m="SF"}else{m="OT";return false}return true},pa=function(a){oa=h;a=a||navigator.userAgent;a=a.toLowerCase();if(a.indexOf("windows ca")!=-1)z="WMB";else if(a.indexOf("windows")!=-1)z="WIN";else if(a.indexOf("ipad")!=-1)z="IPA";else if(a.indexOf("ipod")!=
-1)z="IPO";else if(a.indexOf("iphone")!=-1)z="IPH";else if(a.indexOf("macintosh")!=-1)z="MAC";else if(a.indexOf("symbian")!=-1)z="SYM";else if(a.indexOf("android")!=-1)z="AND";else if(a.indexOf("linux")!=-1)z="LIN";else{z="OTH";return false}return true},m,q,z,oa;na();pa();n.client={identify:function(a){return na(a)&&pa(a)},getBrowserName:function(){return m},getBrowserVersion:function(){return q*1},getBrowser:function(){return m+(q||"")},getOSName:function(){return z},getOS:function(){return z+(oa||
"")},canKill:function(){return m!="IE"},canAsyncJS:function(){return!(m=="OP"||m=="IE"&&q<10||m=="FF"&&q<3.6)},canDeferJS:function(){return m=="IE"||m=="SF"&&q>=4},canKillSyncJS:function(){return false},canPrecache:function(){return!(m==="IE"&&q<=7)},preCacheType:function(){return m==="OP"||m==="CR"||m==="IE"||m==="SF"?"image":"object"},useDelayedWrite:function(){return m==="IE"&&q>=7},useReadyState:function(){return m==="IE"},canWait:function(){return b.waitLatency!==false&&(m!="IE"||q>=7)},canAccelerate:function(a){return(a&&
a instanceof b.Container?a.tagAcceleration||false:true)&&this.inWhitelist()},inWhitelist:function(){return m==="IE"&&q>=7&&q<=9||m==="FF"&&q>=3||m==="CR"&&q>=6},isBodyAppendSafe:function(){return m!="IE"},dataReplacement:function(){return m=="FF"?"about:blank":null},srcReplacement:function(a){b.util.log("srcReplacement("+m+") - "+a.nodeName+" / parent = "+a.parentNode.nodeName,"debug");return m=="FF"||m=="IE"&&q>=9?"about:blank":m=="IE"?a.nodeName=="IMG"?!a.parentNode.removeChild(a):false:null},textReplacement:function(){return m==
"FF"?"about:blank":null},isExecSafeOnload:function(){return false}};n=b;a:switch(b.client.getOS()){case "WIN":case "MAC":case "LIN":v=50;break a;default:v=100}n.POLL_INTERVAL=v;b.Rule=function(a){if(typeof a!="object")throw Error("`options` required for TMAN.Rule");this.likeOR=a.likeOR||[];if(typeof this.likeOR!="object")this.likeOR=[this.likeOR];this.likeAND=a.likeAND||[];if(typeof this.likeOR!="object")this.likeAND=[this.likeAND];this.equals=a.equals||[];if(typeof this.equals!="object")this.equals=
[this.equals];this.greaterThan=typeof a.greaterThan!="undefined"?a.greaterThan:false;this.lessThan=typeof a.lessThan!="undefined"?a.lessThan:false;this.reverseMatch=a.reverseMatch||false};b.Rule.prototype={test:function(a){var e;if(a===null||typeof a=="undefined")b.util.log("`subject` required for TMAN.Rule","error");else{if(this.greaterThan&&a<=this.greaterThan||this.lessThan&&a>=this.lessThan)return this.reverseMatch?true:false;var d=this.equals.length;if(d){for(e=false;d--;)a==this.equals[d]&&
(e=true);if(!e)return this.reverseMatch?true:false}for(var f=[this.likeOR,this.likeAND],g=2,a=a.toString();g--;)if(d=f[g].length){for(e=false;d--;)if(a.indexOf(f[g][d])>-1)e=true;else if(g===1)return this.reverseMatch?true:false;if(!e)return this.reverseMatch?true:false}return this.reverseMatch?false:true}}};b.MAX_URL_LENGTH=2E3;b.CONVERSION_PARAMETERS=["levrev","levresdes","levordref"];b.Track=function(a,e){if(a){if(!(a instanceof b.Container))throw Error("container must be a TMAN.Container");this._container=
a;this._container.track=this}e||(e={});this.setOptions(e)};b.Track.prototype={setOptions:function(a){for(var e=false,d=["callback","campaignEvent","clientname","sessionTimeout","testMode"],f,g=0;f=d[g++];)if(typeof this[f]=="undefined"&&a[f]!="undefined"){this["_"+f]=a[f];e=true}if(typeof this._campaignEvent!=="undefined"){if(!(this._campaignEvent instanceof b.CampaignEvent))throw Error("campaignEvent must be a TMAN.CampaignEvent");}else this._campaignEvent=new b.CampaignEvent;if(this._container){if(typeof this._container.account!==
"undefined")this._clientname=this._container.account;if(typeof this._container.sessionTimeout!=="undefined")this._sessionTimeout=this._container.sessionTimeout}if(typeof this._sessionTimeout==="undefined")this._sessionTimeout=1800;if(!this._clientname)throw Error("must have a clientname (either in options, or from container.account");this.session=new b.Session(this._clientname,this._sessionTimeout);return e},getCampaignEvent:function(){return this._campaignEvent},setReferrer:function(a){this._campaignEvent.setReferrer(a)},
getReferrer:function(){return this._campaignEvent.getReferrer()},getLocation:function(){return this._campaignEvent.getLocation()},setLocation:function(a){this._campaignEvent.setLocation(a)},setParamsFromQueryString:function(){var a=this._campaignEvent.getLocationParams();return this._campaignEvent.setOptions({campaignId:a.tmcampid,placementRef:a.tmplaceref,clickRef:a.tmclickref,eventType:a.tmad==="i"?b.CampaignEvent.VIEW:a.tmad==="c"?b.CampaignEvent.CLICK:h})},gettmParams:function(){tmParam=g.tmParam;
if(typeof tmParam==="undefined")return false;var a={campaignId:tmParam.tmcampid,placementRef:tmParam.tmplaceref,clickRef:tmParam.tmclickref,eventType:tmParam.tmad==="i"?b.CampaignEvent.VIEW:tmParam.tmad==="c"?b.CampaignEvent.CLICK:h};this._custom=tmParam.tmcustom;for(var e=0;key=b.CONVERSION_PARAMETERS[e++];)if(typeof tmParam[key]!=="undefined"){this["_"+key]=tmParam[key];this._isConversion=true}return this._campaignEvent.setOptions(a)},_getContainerParam:function(a){if(!this._container)throw Error("can't call getContainerParams if you haven't passed a container in the constructor");
a=b.getParam(a,this._container);return a==""?h:a},getContainerParams:function(){if(!this._container)throw Error("can't call getContainerParams if you haven't passed a container in the constructor");var a=this._getContainerParam("tmad"),a=a==="i"?b.CampaignEvent.VIEW:a==="c"?b.CampaignEvent.CLICK:h,a={campaignId:this._getContainerParam("tmcampid"),placementRef:this._getContainerParam("tmplaceref"),clickRef:this._getContainerParam("tmclickref"),eventType:a};this._custom=this._getContainerParam("tmcustom");
for(var e=0;key=b.CONVERSION_PARAMETERS[e++];){var d=this._getContainerParam(key);if(typeof d!=="undefined"){this["_"+key]=d;this._isConversion=true}}return this._campaignEvent.setOptions(a)},_setHistory:function(a){var e=false,d=this.getHistory(b.CampaignEvent.CLICK);if(d){a.tmch=d;e=true}if(d=this.getHistory(b.CampaignEvent.VIEW)){a.tmvh=d;e=true}return e},settmParams:function(){var a=g.tmParam;if(typeof a==="undefined"){b.util.log("no window.tmParam object","error");return false}var e=false;if(this._campaignEvent.campaignId){a.tmcampid=
this._campaignEvent.campaignId;a.tmad=this._campaignEvent.eventType===b.Track.VIEW?"i":"c";if(this._campaignEvent.placementRef)a.tmplaceref=this._campaignEvent.placementRef;if(this._campaignEvent.clickRef)a.tmclickref=this._campaignEvent.clickRef;e=true}return e=e||this._setHistory(a)},setContainerParams:function(){if(!this._container)throw Error("can't call setContainerParams if you haven't passed a container in the constructor");var a=false;if(this._campaignEvent.campaignId){var e={tmcampid:this._campaignEvent.campaignId,
tmad:this._campaignEvent.eventType===b.Track.VIEW?"i":"c"};if(this._campaignEvent.placementRef)e.tmplaceref=this._campaignEvent.placementRef;if(this._campaignEvent.clickRef)e.tmclickref=this._campaignEvent.clickRef;a=true}(a=a||this._setHistory(e))&&this._container.addParams(e);return a},isConversion:function(){return this._isConversion},getConversionParams:function(){var a,e=0,d;for(d={};a=b.CONVERSION_PARAMETERS[e++];)typeof this["_"+a]!=="undefined"&&(d[a]=this["_"+a]);return d},sessionActive:function(){return this._testMode||
typeof this._clientname==="undefined"?false:this.session.isActive()},setBaseCampaignRule:function(a){if(!a.execute||typeof a.execute!=="function")throw Error("base rule does not have an execute method");return this.baseRule=a},callTrackingServer:function(a){if(this.serverCalled||!this._campaignEvent.campaignId&&!this._isConversion)return false;a=this.getTrackingServerURL(a);if(!a)return false;b.util.appendScript(a.substring(0,b.MAX_URL_LENGTH),false);return this.serverCalled=true},getTrackingServerURL:function(a){if(!a){if(!this._container)throw Error("can't call getTrackingServerURL if you haven't passed a container in the constructor");
a=this._container.serverCall}if(!a){b.util.log("no serverCall specified for the current container","error");return false}var e="_callback"+(new Date).getTime(),a=a+"?tracking=1";if(this._campaignEvent.campaignId){a=a+("&tmcampid="+this._campaignEvent.campaignId+"&tmad="+(this._campaignEvent.eventType===b.Track.VIEW?"i":"c"));this._campaignEvent.placementRef&&(a=a+("&tmplaceref="+encodeURIComponent(this._campaignEvent.placementRef)));this._campaignEvent.clickRef&&(a=a+("&tmclickref="+encodeURIComponent(this._campaignEvent.clickRef)))}if(this._isConversion){var a=
a+("&"+b.String.objectToQuery(this.getConversionParams())),d=this.getHistory(b.CampaignEvent.CLICK);d&&(a=a+("&tmch="+encodeURIComponent(d)));(d=this.getHistory(b.CampaignEvent.VIEW))&&(a=a+("&tmvh="+encodeURIComponent(d)))}this._custom&&(a=a+("&tmcustom="+encodeURIComponent(this._custom)));var f=this;b.Track[e]=function(a){f._callback&&f._callback(a);f.trackingServerCalled=true;delete b.Track[e]};return a+("&jsonp=TMAN.Track."+e)},applyCampaignRules:function(){return this.sessionActive()||!this.baseRule?
false:this.baseRule.execute(this._campaignEvent)},testCampaignRules:function(a){if(this.sessionActive()||!this.baseRule)return false;for(var e=new b.CampaignEvent,d=0;d<a.length;d++){var f=a[d];e.setReferrer(f.referrer);e.setLocation(f.location);if(!this.baseRule.execute(e)){this.reason="base rule failed";return false}for(var g in f.expected)if(f.expected[g]!==e[g]){this.reason=f.name+" failed: value of "+g+" expected to be "+f.expected[g]+" but was "+e[g];return false}}return true},initialize:function(){this._isConversion=
false;this.gettmParams();this._container&&this.getContainerParams();this.setParamsFromQueryString();this.applyCampaignRules();if(this._campaignEvent.campaignId){this.addEventToHistory();this.settmParams();this._container&&this.setContainerParams()}return this._campaignEvent.campaignId},tm2bootstrap:function(){this.initialize()},addEventToHistory:function(){if(!this._campaignEvent.campaignId)return false;var a="his:"+this._campaignEvent.eventType+":"+this._clientname,e=b.storage.get(a)||"";e&&(e=e+
" ");e=e+this._campaignEvent.serialize();b.storage.set(a,e,301536E3);return true},getHistory:function(a){return b.storage.get("his:"+a+":"+this._clientname)||false}};b.LandingPageRule=function(a){if(!a)throw Error("options required for TMAN.LandingPageRule");if(typeof a!="object")throw Error("options passed to TMAN.LandingPageRule is not an object");if(!a.campaignId)throw Error("No campaignId specified for call to TMAN.LandingPageRule");this.campaignId=a.campaignId;if(!a.match)throw Error("No match function specified for call to TMAN.LandingPageRule");
this.match=a.match;if(!a.rulePriority)a.rulePriority=1;this.rulePriority=a.rulePriority;this.match=a.match;this.clickRef=a.clickRef;this.placementRef=a.placementRef;this.subrules=[]};b.LandingPageRule.prototype={addCampaignRule:function(a){if(!(a instanceof b.LandingPageRule))throw Error("rule argument must be a TMAN.LandingPageRule object");this.subrules.push(a);this.subrules.length>1&&this.subrules.sort(function(a,b){return b.rulePriority-a.rulePriority});return a},execute:function(a){if(!(a instanceof
b.CampaignEvent))throw Error("argument to execute needs to be a TMAN.CampaignEvent");var e=this.match(a);if(!e)return false;var e=typeof e==="object"?e:{},d=e.campaignId||this.campaignId;if(d)a.campaignId=d;if(d=e.placementRef||this.placementRef)a.placementRef=d;if(d=e.clickRef||this.clickRef)a.clickRef=d;if(e=e.viewEvent||this.viewEvent)a.viewEvent=e;for(e=0;e<this.subrules.length;e++)if(this.subrules[e].execute(a))break;return true}};var va="facebook linkedin bebo twitter orkut friendster livejournal blogspot wordpress friendfeed myspace digg reddit stumbleupon twine yelp mixx delicious tumblr disqus intensedebate plurk slideshare backtype netvibes mister-wong diigo flixster youtube vimeo 12seconds zooomr identi jaiku flickr imeem dailymotion photobucket fotolog smugmug classmates myyearbook mylife tagged brightkite ning hi5 yuku cafemom xanga soundcloud asmallworld badoo bigdadda biip blogster buzznet couchsurfing cross cyworld focus fotolog foursquare gather geni hyves itsmy kiwibox lunarstorm mixi mocospace multiply myheritage myopera netlog opendiary plaxo quora qzone renren ryze skyrock socialvibe sonico travbuddy trombi viadeo wayn xanga xing".split(" ");
b.LandingPageRule.matchSocial=function(a,b){var d=a.getReferrerDomain(),f=va.slice(0);b&&f.push(b);f="\\.("+f.join("|")+")\\.";return d.match(RegExp(f))};var wa="google yahoo msn bing aol lycos ask altavista netscape cnn looksmart about mamma alltheweb gigablast voila virgilio live baidu alice yandex najdi club-internet mama seznam search szukaj netsprint google.interia szukacz yam pchome search.conduit search.bt search.mywebsearch search.virginmedia search.sky uk.search-results aolsearch.aol search.alot search.orange search.aol uk.search.yahoo search.babylon search.aol blekko chacha naver nate duckduckgo entireweb faroo info go hakia leapfish monstercrawler dmoz rambler omgili spezify webcrawler teoma dogpile excite hotbot genieknows vivisimo a9 goodsearch guruji yummly goby".split(" ");
b.LandingPageRule.matchSEO=function(a,b){var d=a.getReferrerDomain(),f=wa.slice(0);b&&f.push(b);f="\\.("+f.join("|")+")\\.";return d.match(RegExp(f))?{placementRef:d,clickRef:a.getReferrerKeywords()}:false};b.LandingPageRule.matchSecureSEO=function(a){var b=a.getReferrerDomain();if(!b.match(/\.(google)\./))return false;a=a.getReferrerParams().esrc;return!a||a!=="s"?false:{placementRef:b}};b.LandingPageRule.Test=function(a){if(!a)throw Error("options required for TMAN.LandingPageRule.Test");if(typeof a!=
"object")throw Error("options passed to TMAN.LandingPageRule.Test is not an object");if(!a.expected)throw Error("No expected specified for call to TMAN.LandingPageRule.Test");if(typeof a.expected!="object")throw Error("expected is not an object");this.expected=a.expected;if(!a.name)throw Error("No name specified for call to TMAN.LandingPageRule.Test");this.referrer=a.referrer;this.location=a.location;this.name=a.name};b.CampaignEvent=function(a){a||(a={});this.setOptions(a);this.referrer=j.referrer;
this.location=j.location.toString()};b.CampaignEvent.CLICK=0;b.CampaignEvent.VIEW=1;b.CampaignEvent.prototype={setOptions:function(a){for(var e=false,d=["campaignId","placementRef","clickRef","eventType"],f,g=0;f=d[g++];)if(typeof a[f]!=="undefined"){this[f]=a[f];e=true}if(typeof this.eventType==="undefined")this.eventType=b.CampaignEvent.CLICK;return e},setReferrer:function(a){this.referrer=a},getReferrer:function(){return this.referrer},setLocation:function(a){this.location=a},getLocation:function(){return this.location},
getReferrerParams:function(a){a=a||this.referrer;if(!a)return{};a=a.split("?");return!a.length==2?{}:b.String.queryToObject(a[1])},getLocationParams:function(a){a=a||this.location;if(!a)return{};a=a.split("?");return!a.length==2?{}:b.String.queryToObject(a[1])},getReferrerKeywords:function(a){a=a||this.referrer;return(a=/[?&](q|p|query|encquery|terms|rdata|szukaj|k|qt|qs|wd|text)=([^&]*)/.exec(a))?decodeURIComponent(a[2].replace(/\+/g," ")):""},getReferrerDomain:function(a){return(a=a||this.referrer)?
a.replace(/^https?:\/\/([^\/]+)\/.*$/,"$1"):""},serialize:function(){var a=new Date,a=parseInt((a.getTime()+a.getTimezoneOffset()*6E4)/1E3,10);return[a,this.campaignId,b.util.scramble(this.placementRef||""),b.util.scramble(this.clickRef||"")].join(";")}};LEVU={};LEVU.ABoH=b.util.append;LEVU.AIF=b.util.appendIframe;LEVU.GPR=b.util.getProtocol;LEVU.GP=b.String.getParam;LEVU.SP=b.String.setParam;LEVU.OTQ=b.String.objectToQuery;LEVU.QTO=b.String.queryToObject;LEVU.RX=b.String.regEx;LEVU.SS=b.String.subString;
LEVU.FD=b.String.isFound;LEVU.GS=b.String.getStem;LEVU.PR=b.String.printR;LEVU.LES=b.String.lescape;LEVU.DLE=b.String.doubleLescape;LEVU.WIF=b.util.writeIframe;LEVU.AJS=b.util.appendScript;LEVU.CIm=b.util.createImage;LEVU.LE=b.util.log;LEVU.IIF=b.util.isInIframe;LEVU.WJS=b.util.writeJS;LEVU.PKV=b.util.parseKeyValue;LEVU.SKV=b.util.setKeyValue;LEVU.ES=b.hack.evalScript;LEVU.SQ=b.hack.getScriptParams;LEVU.FS=b.hack.findScript;LEVU.ADW=b.hack.addDelayedWrite;LEVU.IDW=b.hack.initDelayedWrite;LEVU.WDW=
b.hack.writeDelayedWrite;LEVU.DS=b.num.doSample;LEVU.GetCB=b.num.getCacheBuster;LEVU.GC=function(a){return b.util.cookie(a)};LEVU.SC=function(a,e,d,f){b.util.cookie(a,e,{path:d,expires:f})};try{LEVU.ES("lu.js");var Y=LEVU.SQ("lu.js");Y&&b.util.log("Querystring ["+Y+"] found on lu.js, no longer supported","FATAL")}catch(ya){b.util.log("Error excuting LEVU.SQ on bootStrap of lu.js","ERROR")}b.DOMQ=function(a){this.el=a||j};b.DOMQ.factory=function(a){for(var e=[],d=0,f=a.length;d<f;d++)e[d]=new b.DOMQ(a[d]);
return e};b.DOMQ.prototype={id:function(a){if(!this.el)return this;if(!this.el.getElementById)return j.getElementById(a);this.el=this.el.getElementById(a);return this},tag:function(a,b){if(!this.el)return this;this.el=this.el.getElementsByTagName(a)[b||0];return this},name:function(a,b){if(!this.el)return this;this.el=this.getElementsByName(a)[b||0];return this},className:function(a,b){if(!this.el)return this;this.el=this.getElementsByClassName(a)[b||0];return this},isAncestor:function(a){var b=this.el;
if(b){for(;a;){if(a==b&&a!=b)return true;a=a.parentNode}return false}},getElementsByName:function(a){if(!this.el)return[];a=j.getElementsByName(a);if(this.el===j)return a;for(var b=[],d=0,f=a.length;d<f;d++)this.isAncestor(a[d])&&b.push(a[d]);return b},getElementsByClassName:function(a){if(!this.el)return[];for(var b=this.el.getElementsByTagName("*"),a=a.replace(/\-/g,"\\-"),a=RegExp("(?:^|\\s)"+a+"(?:\\s|$)"),d=[],f=0,g=b.length;f<g;f++)a.test(b[f].className)&&d.push(b[f]);return d},match:function(a,
e){return(new b.String(this.toString())).match(a,e)},replace:function(a,e){return(new b.String(this.toString())).replace(a,e)},toString:function(){return!this.el?"":this.el==j?this.el.documentElement.innerHTML:this.el.value?this.el.value:this.el.innerHTML}};var Y=b,A={html:function(){return new b.DOMQ},id:function(a){return A._html.id(a)},tag:function(a,b){return A._html.tag(a,b)},name:function(a,b){return A._html.name(a,b)},className:function(a,b){return A._html.className(a,b)},head:function(){return A.tag("head")},
body:function(){return A.tag("body")}};A._html=A.html();n=function(a){for(var e in a){var d=a[e],f="";typeof d=="string"?f=A.id(d):d instanceof RegExp?f=A.html().match(d,"$1"):d instanceof Array?f=A.id(d[0]).match(d[1],"$1"):typeof d=="function"&&(f=d(A)||"");b.conf.param[e]=""+f}};g.LEV_DT&&n(g.LEV_DT);Y.DT=n})(this);this.LEV=this.LEV||{};this.Lescape=TMAN.String.escape;this.DoubleLescape=TMAN.String.doubleEscape;LEV.extend||(LEV.extend=TMAN.util.extend);LEV.String||(LEV.String=TMAN.String);
LEV.StringBuilder||(LEV.StringBuilder=TMAN.StringBuilder);LEV.DOMQ||(LEV.DOMQ=TMAN.DOMQ);LEV.DT||(LEV.DT=TMAN.DT);LEV.onDOM||(LEV.onDOM=TMAN.onDomReady);
LEV.bootStrap=function(){TMAN.conf.id=window.tmPageId;if(TMAN.conf.landingPageMins&&TMAN.SessionCookie.isActive(TMAN.conf.landingPageMins)){TMAN.util.log("Session cookie still active and tmOPV set to ["+TMAN.conf.landingPageMins+"] minutes","MESSAGE");return false}if(TMAN.conf._lastContainerId==TMAN.conf.id)return false;TMAN.conf._tagStr="";TMAN.conf._tagStr=TMAN.util.cookie("tmStaging")?TMAN.conf.baseURL.replace(/(.*?)\/\/(.*?)\.(.*)/,"$1//tagstaging.$3"):TMAN.conf.baseURL;TMAN.conf._tagStr=TMAN.conf._tagStr+
"/tmpageid="+TMAN.conf.id;TMAN.conf.lastContainerId=TMAN.conf.id;TMAN.conf._tagStr=TMAN.conf._tagStr+("&levyouruid="+Math.random());TMAN.conf._tagStr=TMAN.conf._tagStr+("&tmsecmode="+(TMAN._secure?"S":"N"));var g=TMAN.conf._tagStr+LEV_TMIFPS();if(TMAN.conf.param&&(TMAN.conf.param.tmcampid||TMAN.conf.param.levrev||TMAN.conf.param.levresdes)){window.tmCBRequired=true;TMAN.conf._callbackRequired=true}g=g+"&tmtag=js";TMAN.conf.enableJSCall&&(window.tm2BootAsync?TMAN.util.appendScript(g,false,{defer:false}):
TMAN.syncSafe?TMAN.util.writeScript(g):TMAN.util.log("Unable to initiliaze container, !syncSafe && !tm2BootAsync","fatal"))};function LEV_TMIFPS(){var g=new LEV.StringBuilder;if(typeof TMAN.conf.param!="undefined")for(var h in TMAN.conf.param){var l=TMAN.conf.param[h],k=typeof l;if(k==="function"){l=l();k=typeof l}h&&(l&&(k=="number"||k=="string"||k=="boolean"))&&g.append("&",h,"=",TMAN.String.doubleEscape(l))}return g.toString()}
function LEV_TMTCB(){window.tmTrack=void 0;window.tmTrackWaiting&&LEV_TMIFCB()}
var LEV_TMIFCB=function(){function g(){window.LEV_DT&&LEV.DT(window.LEV_DT);if(window.LEV_DTD)for(var g=0;g<LEV_DTD.length;g++)LEV_DTD[g]();if(typeof window.tmDisableIframe!="undefined")TMAN.conf._disableIframe=window.tmDisableIframe;if(typeof window.tmCBRequired!="undefined")TMAN.conf._callbackRequired=window.tmCBRequired;if(location.hash=="#tmtest")parent.location=document.referrer+"#"+h();try{TMAN.util.log("referrer="+document.referrer,"DEBUG");if(typeof TMAN.conf.param=="object"){var k="",r;for(r in TMAN.conf.param)typeof TMAN.conf.param[r]!=
"undefined"&&(k=k+("\t"+r+"=>"+TMAN.conf.param[r]+"\n"));k||(k="<empty>")}TMAN.util.log("TMAN.conf.param contents\n"+k,"DEBUG");typeof tmOPV!="undefined"&&TMAN.util.log("tmOPV="+TMAN.conf.landingPageMins,"DEBUG");TMAN.util.log("tmBaseURL="+TMAN.conf.baseUrl,"DEBUG");TMAN.util.log("tmPageId="+TMAN.conf.id,"DEBUG")}catch(j){TMAN.util.log("logging error on of tmPageId or tmBaseURL probably does not exits"+j.message,"FATAL")}if(TMAN.conf._disableIframe){if(TMAN.conf.param&&(TMAN.conf.param.tmad||TMAN.conf.param.levrev||
TMAN.conf.param.levresdes||TMAN.conf.param.levordref)||TMAN.conf._callbackRequired)if(LEV.onDOM.isReady()){g=h("image");TMAN.util.appendImage(g);TMAN.util.log("Image written: "+g)}else LEV.onDOM(function(){var g=h("image");TMAN.util.appendImage(g);TMAN.util.log("Image written: "+g,"DEBUG")})}else if(LEV.onDOM.isReady()){g=h("iframe");TMAN.util.appendIframe(g);TMAN.util.log("Iframe written: "+g,"DEBUG")}else LEV.onDOM(function(){var g=h("iframe");TMAN.util.appendIframe(g);TMAN.util.log("Iframe written: "+
g,"DEBUG")})}function h(g){g=TMAN.conf._tagStr+LEV_TMIFPS()+(typeof TMAN.conf.tmbtpos==="number"?"&tmbtpos="+TMAN.conf.tmbtpos:"")+(g?"&tmtag="+g:"");TMAN.util.log("URL for callback: "+g,"DEBUG");return g}return function(){TMAN.conf._writeImmediately=window.tmImmediate||false;if(typeof TMAN!="undefined"&&typeof TMAN.doTags==="function"){TMAN.conf.tmbtpos=TMAN.currentPosition;g();TMAN.doTags(TMAN.currentPosition,window.tm2BootAsync)}else if(TMAN.conf._writeImmediately)g();else LEV.onDOM(g)}}();
"undefined"===typeof TMAN.conf&&(TMAN.conf={param:{}},"undefined"===typeof tmPageId&&("undefined"===typeof tmContId?TMAN.util.log("tmContId or tmPageId not defined for TagMan container, it's compulsary","FATAL"):tmPageId=tmContId));TMAN.util.extend(TMAN.conf,{_lastContainerId:0,_tagStr:"",_callbackRequired:!1,_disableIframe:!1,enableJSCall:!0,enableURLTracking:!0,_writeImmediately:!1});TMAN.position=TMAN.position||{};
TMAN.util.extend(TMAN.position,{PRE_HEAD:0,TOP_HEAD:1,BOTTOM_HEAD:2,TOP_BODY:3,BOTTOM_BODY:31,DOM_COMPLETE:32,WINDOW_LOADED:33,END:64});"string"===typeof tmBaseUrl&&(TMAN.util.extend(TMAN.conf,{baseURL:window.tmBaseUrl,id:window.tmPageId,landingPageMins:window.tmOPV||!1,bootstrap:"undefined"===typeof tmBootStrap?!0:window.tmBootStrap,param:window.tmParam||{}}),TMAN.conf.bootstrap&&LEV.bootStrap());
TMAN.doTags=TMAN.doTags||function(g){var h=window.TMAN;if(g>=(typeof(window.tm2BootPosition!="undefined")?window.tm2BootPosition:h.position.TOP_BODY)&&typeof h.conf.TM2initialised==="boolean"&&!h.conf.TM2initialised){h.conf.TM2initialised=true;LEV.bootStrap()}};
TMAN.tm2initialise=function(g){TMAN.conf.param=TMAN.conf.param||{};if(g.baseURL||g.host&&g.account){window.TMAN.conf.baseURL=g.baseURL||(location.protocol==="https:"?"https://":"http://")+g.host+"/"+g.account+"/"+(g.serverCall||"tman.cgi");window.TMAN.conf.TM2initialised=g.bootstrap?false:true;typeof window.TMAN.Tag==="function"&&TMAN.getContainerByName(g.account).addTags(new TMAN.Tag("TMAN.conf.account=TMAN._containers[0].account;TMAN.conf.id=TMAN._containers[0].id;TMAN.conf.param=TMAN._containers[0].param;window.TMAN.conf.TM2initialised=true; LEV.bootStrap();",
{position:typeof window.tm2BootPosition!="undefined"?window.tm2BootPosition:TMAN.position.TOP_BODY,async:window.tm2BootAsync||false,movable:true,bootstrapper:true}))}else{TMAN.util.log("Problem with container code conf.baseURL and host/account not available","FATAL");TMAN.conf.TM2initialised=true}};
"function"!==typeof TMAN.Container&&(TMAN.Container=function(g,h,l){var k=window.TMAN.conf;k.account=g||k.account;k.id=h||k.id;k.host=l.host||DEFAULT_HOST;k.tags=l.tags||[];k.async="async"in l?l.async:false;k.tagsBlockingTimeout=l.tagsBlockingTimeout||0;k.sessionTimeout=l.sessionTimeOut||3600;k.landingPageConteiner=l.landingPageContainer||false;k.bootstrap="bootstrap"in l?l.bootstrap:true;k.enableJSCall="enableJSCall"in l?l.enableJSCall:true;k.param=k.param||{};k.serverCall=l.serverCall||k.serverCall||
"tman.cgi/";TMAN.addContainer=TMAN.addContainer||function(){return true};TMAN.tm2initialise(TMAN.container)});TMAN.addContainer=TMAN.addContainer||function(){return true};"function"===typeof window.TMAN.asyncLoader&&(window.TMAN.asyncLoader(),window.TMAN.asyncLoader=void 0);this.TMAN=this.TMAN||{};TMAN.MAP=function(){this.maps=[]};
TMAN.MAP.prototype={addMap:function(g){g=new TMAN.MAP.HashMap(g);this.maps[g.head.ParentCId()]=g},addMapIf:function(g,h){var l=new TMAN.MAP.HashMap(h);l.head.ParentCId()==g&&(this.maps[g]=l)},search:function(g){var g=TMAN.MAP.B92SHA1(g),h,l;for(l in this.maps)if(h=this.maps[l])return h.Search(g)}};
TMAN.MAP.Head=function(g){var h;this.ok=true;this.error="";if(g&&g.length!=0){this.v=TMAN.B92.desmall(g.substr(0,2));if(this.v!=2){this.ok=false;this.error="Version "+this.v+" is unsupported"}else{this.hlen=TMAN.B92.desmall(g.substr(2,1));this.clen=TMAN.B92.desmall(g.substr(3,1));this.cid=TMAN.B92.desmall(g.substr(4,2));this.olen=TMAN.B92.desmall(g.substr(6,1));this.oto=TMAN.B92.desmall(g.substr(7,2));h=TMAN.B92.desmall(g.substr(9,1));this.schema=g.substr(10,h);this.maps=g.substr(10+h)}}};
TMAN.MAP.Head.prototype={Version:function(){return this.v},HashLen:function(){return this.hlen},CIdLen:function(){return this.clen},ParentCId:function(){return this.cid},OtherLen:function(){return this.olen},Maps:function(){return this.maps},OPVTO:function(){return this.oto},Schema:function(){return this.schema}};
TMAN.MAP.SHA1=function(g){var h,l,k,r=Array(80),j=1732584193,B=4023233417,b=2562383102,t=271733878,u=3285377520,o,w,x,F;o=g.length;var C=[];for(h=0;h<o-3;h=h+4){l=g.charCodeAt(h)<<24|g.charCodeAt(h+1)<<16|g.charCodeAt(h+2)<<8|g.charCodeAt(h+3);C.push(l)}switch(o%4){case 0:h=2147483648;break;case 1:h=g.charCodeAt(o-1)<<24|8388608;break;case 2:h=g.charCodeAt(o-2)<<24|g.charCodeAt(o-1)<<16|32768;break;case 3:h=g.charCodeAt(o-3)<<24|g.charCodeAt(o-2)<<16|g.charCodeAt(o-1)<<8|128}for(C.push(h);C.length%
16!=14;)C.push(0);C.push(o>>>29);C.push(o<<3&4294967295);for(g=0;g<C.length;g=g+16){for(h=0;h<16;h++)r[h]=C[g+h];for(h=16;h<80;h++)r[h]=(r[h-3]^r[h-8]^r[h-14]^r[h-16])<<1|(r[h-3]^r[h-8]^r[h-14]^r[h-16])>>>31;l=j;o=B;w=b;x=t;F=u;for(h=0;h<80;h++){k=r[h];k=h<20?(l<<5|l>>>27)+(o&w|~o&x)+F+k+1518500249&4294967295:h<40?(l<<5|l>>>27)+(o^w^x)+F+k+1859775393&4294967295:h<60?(l<<5|l>>>27)+(o&w|o&x|w&x)+F+k+2400959708&4294967295:(l<<5|l>>>27)+(o^w^x)+F+k+3395469782&4294967295;F=x;x=w;w=o<<30|o>>>2;o=l;l=k}j=
j+l&4294967295;B=B+o&4294967295;b=b+w&4294967295;t=t+x&4294967295;u=u+F&4294967295}return[j,B,b,t,u]};TMAN.MAP.B92SHA1=function(g){return TMAN.B92.encode(TMAN.MAP.SHA1(g),25)};TMAN.MAP.Map=function(g,h){if(g&&h){this.head=h;this.hash=g.substr(0,h.HashLen());this.Cid=TMAN.B92.desmall(g.substr(h.HashLen(),h.CIdLen()));this.Other=TMAN.B92.desmall(g.substr(h.HashLen()+h.CIdLen(),h.OtherLen()))}};
TMAN.MAP.Map.prototype={Hash:function(){return this.hash},ContainerId:function(){return this.Cid},Header:function(){return this.head},OncePerVisit:function(){return(this.Other&1)==1?true:false}};TMAN.MAP.HashMap=function(g){this.text=g;this.head=new TMAN.MAP.Head(this.text)};TMAN.MAP.HashMap.prototype.Search=function(g){for(var h=this.head,l=h.HashLen(),k=l+h.CIdLen()+h.OtherLen(),g=g.substr(g.length-l),l=h.Maps(),r=0;;){r=l.indexOf(g,0);if(0%k==0)return new TMAN.MAP.Map(l.substr(r,k),h)}};







TMAN.position.CUSTOM_1=34;
TMAN.position.CUSTOM_2=35;
TMAN.position.CUSTOM_3=36;
TMAN.position.CUSTOM_4=37;
TMAN.position.CUSTOM_5=38;
TMAN.position.SIGNUP=39;
TMAN.position.UNSUB=40;
TMAN.position.PRINT=41;
TMAN.position.SHARE=42;
TMAN.position.RSS=43;
TMAN.position.NEWSLETTER=44;
TMAN.position.DOWNLOAD=45;
TMAN.position.EXCEL=46;
TMAN.position.PDF=47;
TMAN.position.CONTACTS=48;
TMAN.position.SURVEY_START=49;
TMAN.position.SURVEY_COMPLETE=50;
TMAN.position.CHAT=51;
TMAN.position.COMMENTED=52;
TMAN.position.RATED=53;
TMAN.position.CARTADD=54;
TMAN.position.FB_LIKE=55;
TMAN.position.FB_FRIEND=56;
TMAN.position.FB_JOIN=57;
TMAN.position.FB_FIND=58;
TMAN.position.TW_FOLLOW=59;
TMAN.position.FUNNEL_A_1=60;
TMAN.position.FUNNEL_A_2=61;
TMAN.position.FUNNEL_A_3=62;
TMAN.position.FUNNEL_A_4=63;
TMAN.position.FUNNEL_A_5=65;
TMAN.position.FUNNEL_B_1=66;
TMAN.position.FUNNEL_B_2=67;
TMAN.position.FUNNEL_B_3=68;
TMAN.position.FUNNEL_B_4=69;
TMAN.position.FUNNEL_B_5=70;
TMAN.position.FUNNEL_C_1=71;
TMAN.position.FUNNEL_C_2=72;
TMAN.position.FUNNEL_C_3=73;
TMAN.position.FUNNEL_C_4=74;
TMAN.position.FUNNEL_C_5=75;
TMAN.position.EXIT_BUTTON=76;
TMAN.position.EXIT_BUTTON_RETAIL=77;
TMAN.position.EXIT_BUTTON_ONLINE=78;
TMAN.position.ADD_PARAMS=79;
(function () {
	var product_level = -1;

	function getParam(strVarName) {
		return TMAN.conf.param[strVarName];
	}

	function isParamDefined(strVarName) {
		return typeof TMAN.conf.param[strVarName] !== "undefined";
	}

	function isParamValid(strVarName) {
		return isParamDefined(strVarName) && TMAN.conf.param[strVarName] !== "";
	}

	function searchArray(needle, array) {
		var i = 0;
		var len = array.length;

		for (var i = 0; i < len; i++) {
			if (array[i] === needle) {
				return i;
			}
		}

		return -1;
	}

	var campaign_name_list = ["washing machine","washers", "PrintSolutions", "Mobile devices", "smartphones", "printers-multifunction", "home-appliances", "printers-multifunction"];

	var campaign_path_list = ["/index.php", "/fr/galaxynote3+gear/", "/fr/printinginnovation/", "/fr/pure-experience/crystalblue", "/fr/pure-experience/lave-linge-crystalblue", "/fr/pure-experience/#lave-linge-crystalblue", "/fr/pure-experience/lave-linge-crystalblue/", "/fr/pure-experience/#refrigerateur-foodshowcase", "/fr/pure-experience/refrigerateur-foodshowcase", "/fr/pure-experience/refrigerateur-foodshowcase/", "/fr/business/microsite-smart-printers/"];

	var microsite_path_list = ["/fr/ecobubble/", "/fr/galaxynote3+gear/spec.html", "/fr/galaxynote3+gear/color.html", "/fr/galaxynote3+gear/video.html", "/fr/galaxynote3+gear/gift.html", "/fr/galaxynote3+gear/offre.html", "/fr/galaxynote3+gear/ilmn.html", "/fr/pure-experience/lave-linge-crystalblue/design", "/fr/pure-experience/lave-linge-crystalblue/simplicite", "/fr/pure-experience/lave-linge-crystalblue/intelligence", "/fr/pure-experience/lave-linge-crystalblue/controle", "/fr/pure-experience/lave-linge-crystalblue/fiche-produit", "/fr/pure-experience/lave-linge-crystalblue/ecobubble", "/fr/pure-experience/lave-linge-crystalblue/silence", "/fr/pure-experience/#lave-linge-crystalblue/design", "/fr/pure-experience/#lave-linge-crystalblue/simplicite", "/fr/pure-experience/#lave-linge-crystalblue/intelligence", "/fr/pure-experience/#lave-linge-crystalblue/controle", "/fr/pure-experience/#lave-linge-crystalblue/fiche-produit", "/fr/pure-experience/#lave-linge-crystalblue/ecobubble", "/fr/pure-experience/#lave-linge-crystalblue/silence", "/fr/pure-experience/#refrigerateur-foodshowcase/design", "/fr/pure-experience/refrigerateur-foodshowcase/design", "/fr/pure-experience/#refrigerateur-foodshowcase/accessibilite", "/fr/pure-experience/refrigerateur-foodshowcase/accessibilite", "/fr/pure-experience/#refrigerateur-foodshowcase/intelligence", "/fr/pure-experience/refrigerateur-foodshowcase/intelligence", "/fr/pure-experience/#refrigerateur-foodshowcase/metal-cooling", "/fr/pure-experience/refrigerateur-foodshowcase/metal-cooling", "/fr/pure-experience/#refrigerateur-foodshowcase/fiche-produit", "/fr/pure-experience/refrigerateur-foodshowcase/fiche-produit", "/fr/pure-experience/refrigerateur-foodshowcase/naturel", "/fr/pure-experience/#refrigerateur-foodshowcase/naturel", "/fr/pure-experience/refrigerateur-foodshowcase/intelligent", "/fr/pure-experience/#refrigerateur-foodshowcase/intelligent"];

	var product_levels = ["product_local_type", "product_local_sub_type", "product_local_codes"];

	TMAN.samsung = {};

	TMAN.samsung.isActiveCampaign = function () {
		return isParamDefined("product_local_type") && searchArray(getParam("product_local_type"), campaign_name_list) > -1;
	};

	TMAN.samsung.isCampaignHash = function () {
		return searchArray(document.location.pathname+document.location.hash, campaign_path_list) > -1;
	};

	TMAN.samsung.isCampaign = function () {
		return isParamDefined("product_local_group") && getParam("product_local_group") === "campaign";
	};

	TMAN.samsung.isHomepage = function () {
		return ((document.location.pathname === "/fr/") || ( document.location.pathname === "/fr/business/") || ( document.location.pathname === "/fr/home/") || (document.location.pathname === "/fr/business/home/") || ( document.location.pathname === "/fr/home") || (document.location.pathname === "/fr/business/home"));
	};

	TMAN.samsung.isMicrositeHash = function () {
		return searchArray(document.location.pathname+document.location.hash, microsite_path_list) > -1;
	};

	TMAN.samsung.isMicrosite = function () {
		return searchArray(document.location.pathname, microsite_path_list) > -1;
	};

	TMAN.samsung.isProduct = function () {
		if (product_level > -1) {
			return product_level;
		}

		var i;
		var len = product_levels.length;
		var product_lvl = 0;

		for (var i = 0; i < len; i++) {
			if (!isParamValid(product_levels[i])) {
				break;
			}

			product_lvl++;
		}

		product_level = product_lvl;
		return product_level;
	};

	TMAN.samsung.isProductDetail = function () {
		return this.isActiveCampaign() && this.isProduct() === 3;
	};

	TMAN.samsung.isRetailerClick = function () {
		return searchArray(document.location.pathname, campaign_path_list) > -1;
	};

	TMAN.samsung.getDescription = (function () {
		var description = "";
		var number = 0;
		var product = 0;

		if (this.isHomepage()) {
			number = 1001;
			description = "Home_Page_View";
		} else if (this.isRetailerClick()) {
			number = 1006;
			description = "Campaign_Landing_Page_View";
		} else if (this.isCampaignHash()) {
			number = 1006;
			description = "Campaign_Landing_Page_View";			
		} else if (this.isMicrositeHash()) {
			number = 1009;
			description = "Microsite_Aux_Page_Views";
		} else if (this.isMicrosite()) {
			number = 1009;
			description = "Microsite_Aux_Page_Views";
		} else if (this.isActiveCampaign()) {
			if (this.isCampaign()) {
				number = 1006;
				description = "Campaign_Landing_Page_View";			
			} else if ((product = this.isProduct()) > 0) {
				if (product == 1) {
					number = 1002;
					description = "Product_Type_Page_View";
				} else if (product == 2) {
					number = 1003;
					description = "Product_SubType_Page_View";
				} else if (product == 3) {
					number = 1004;
					description = "Product_Detail_Page_View";
				}
			}
		}

		if (number > 0) {
			return number.toString()+'_'+description;
		} else {
			throw "No description";
		}
	});
})();

// tm3 async bootstrap
TMAN.doTags(TMAN.currentPosition,true);
